package com.neusoft.bsp.model;

import java.util.Date;

public class codeMaster {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_code_master.CDM_ID
     *
     * @mbg.generated
     */
    private Integer cdmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_code_master.CODE_TYPE
     *
     * @mbg.generated
     */
    private String codeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_code_master.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_code_master.TYPE_CD
     *
     * @mbg.generated
     */
    private String typeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_code_master.CODE_VAL
     *
     * @mbg.generated
     */
    private String codeVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_code_master.SEQ_NO
     *
     * @mbg.generated
     */
    private Integer seqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_code_master.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_code_master.CREATION_DATE
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_code_master.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_code_master.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_code_master.CALL_CNT
     *
     * @mbg.generated
     */
    private Integer callCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_code_master.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_code_master.STS_CD
     *
     * @mbg.generated
     */
    private String stsCd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdm_code_master
     *
     * @mbg.generated
     */
    public codeMaster(Integer cdmId, String codeType, String description, String typeCd, String codeVal, Integer seqNo, String createdBy, Date creationDate, String lastUpdateBy, Date lastUpdateDate, Integer callCnt, String remark, String stsCd) {
        this.cdmId = cdmId;
        this.codeType = codeType;
        this.description = description;
        this.typeCd = typeCd;
        this.codeVal = codeVal;
        this.seqNo = seqNo;
        this.createdBy = createdBy;
        this.creationDate = creationDate;
        this.lastUpdateBy = lastUpdateBy;
        this.lastUpdateDate = lastUpdateDate;
        this.callCnt = callCnt;
        this.remark = remark;
        this.stsCd = stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdm_code_master
     *
     * @mbg.generated
     */
    public codeMaster() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_code_master.CDM_ID
     *
     * @return the value of cdm_code_master.CDM_ID
     *
     * @mbg.generated
     */
    public Integer getCdmId() {
        return cdmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_code_master.CDM_ID
     *
     * @param cdmId the value for cdm_code_master.CDM_ID
     *
     * @mbg.generated
     */
    public void setCdmId(Integer cdmId) {
        this.cdmId = cdmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_code_master.CODE_TYPE
     *
     * @return the value of cdm_code_master.CODE_TYPE
     *
     * @mbg.generated
     */
    public String getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_code_master.CODE_TYPE
     *
     * @param codeType the value for cdm_code_master.CODE_TYPE
     *
     * @mbg.generated
     */
    public void setCodeType(String codeType) {
        this.codeType = codeType == null ? null : codeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_code_master.DESCRIPTION
     *
     * @return the value of cdm_code_master.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_code_master.DESCRIPTION
     *
     * @param description the value for cdm_code_master.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_code_master.TYPE_CD
     *
     * @return the value of cdm_code_master.TYPE_CD
     *
     * @mbg.generated
     */
    public String getTypeCd() {
        return typeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_code_master.TYPE_CD
     *
     * @param typeCd the value for cdm_code_master.TYPE_CD
     *
     * @mbg.generated
     */
    public void setTypeCd(String typeCd) {
        this.typeCd = typeCd == null ? null : typeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_code_master.CODE_VAL
     *
     * @return the value of cdm_code_master.CODE_VAL
     *
     * @mbg.generated
     */
    public String getCodeVal() {
        return codeVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_code_master.CODE_VAL
     *
     * @param codeVal the value for cdm_code_master.CODE_VAL
     *
     * @mbg.generated
     */
    public void setCodeVal(String codeVal) {
        this.codeVal = codeVal == null ? null : codeVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_code_master.SEQ_NO
     *
     * @return the value of cdm_code_master.SEQ_NO
     *
     * @mbg.generated
     */
    public Integer getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_code_master.SEQ_NO
     *
     * @param seqNo the value for cdm_code_master.SEQ_NO
     *
     * @mbg.generated
     */
    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_code_master.CREATED_BY
     *
     * @return the value of cdm_code_master.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_code_master.CREATED_BY
     *
     * @param createdBy the value for cdm_code_master.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_code_master.CREATION_DATE
     *
     * @return the value of cdm_code_master.CREATION_DATE
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_code_master.CREATION_DATE
     *
     * @param creationDate the value for cdm_code_master.CREATION_DATE
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_code_master.LAST_UPDATE_BY
     *
     * @return the value of cdm_code_master.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_code_master.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for cdm_code_master.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_code_master.LAST_UPDATE_DATE
     *
     * @return the value of cdm_code_master.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_code_master.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for cdm_code_master.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_code_master.CALL_CNT
     *
     * @return the value of cdm_code_master.CALL_CNT
     *
     * @mbg.generated
     */
    public Integer getCallCnt() {
        return callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_code_master.CALL_CNT
     *
     * @param callCnt the value for cdm_code_master.CALL_CNT
     *
     * @mbg.generated
     */
    public void setCallCnt(Integer callCnt) {
        this.callCnt = callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_code_master.REMARK
     *
     * @return the value of cdm_code_master.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_code_master.REMARK
     *
     * @param remark the value for cdm_code_master.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_code_master.STS_CD
     *
     * @return the value of cdm_code_master.STS_CD
     *
     * @mbg.generated
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_code_master.STS_CD
     *
     * @param stsCd the value for cdm_code_master.STS_CD
     *
     * @mbg.generated
     */
    public void setStsCd(String stsCd) {
        this.stsCd = stsCd == null ? null : stsCd.trim();
    }
}