package com.neusoft.bsp.model;

import java.util.Date;

public class dropshipper {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsr_dropshipper.DSR_ID
     *
     * @mbg.generated
     */
    private Integer dsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsr_dropshipper.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsr_dropshipper.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsr_dropshipper.CREATION_DATE
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsr_dropshipper.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsr_dropshipper.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsr_dropshipper.CALL_CNT
     *
     * @mbg.generated
     */
    private Integer callCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsr_dropshipper.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsr_dropshipper.STS_CD
     *
     * @mbg.generated
     */
    private String stsCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsr_dropshipper.REGISTER_DATE
     *
     * @mbg.generated
     */
    private Date registerDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsr_dropshipper
     *
     * @mbg.generated
     */
    public dropshipper(Integer dsrId, String name, String createdBy, Date creationDate, String lastUpdateBy, Date lastUpdateDate, Integer callCnt, String remark, String stsCd, Date registerDate) {
        this.dsrId = dsrId;
        this.name = name;
        this.createdBy = createdBy;
        this.creationDate = creationDate;
        this.lastUpdateBy = lastUpdateBy;
        this.lastUpdateDate = lastUpdateDate;
        this.callCnt = callCnt;
        this.remark = remark;
        this.stsCd = stsCd;
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsr_dropshipper
     *
     * @mbg.generated
     */
    public dropshipper() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsr_dropshipper.DSR_ID
     *
     * @return the value of dsr_dropshipper.DSR_ID
     *
     * @mbg.generated
     */
    public Integer getDsrId() {
        return dsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsr_dropshipper.DSR_ID
     *
     * @param dsrId the value for dsr_dropshipper.DSR_ID
     *
     * @mbg.generated
     */
    public void setDsrId(Integer dsrId) {
        this.dsrId = dsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsr_dropshipper.NAME
     *
     * @return the value of dsr_dropshipper.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsr_dropshipper.NAME
     *
     * @param name the value for dsr_dropshipper.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsr_dropshipper.CREATED_BY
     *
     * @return the value of dsr_dropshipper.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsr_dropshipper.CREATED_BY
     *
     * @param createdBy the value for dsr_dropshipper.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsr_dropshipper.CREATION_DATE
     *
     * @return the value of dsr_dropshipper.CREATION_DATE
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsr_dropshipper.CREATION_DATE
     *
     * @param creationDate the value for dsr_dropshipper.CREATION_DATE
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsr_dropshipper.LAST_UPDATE_BY
     *
     * @return the value of dsr_dropshipper.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsr_dropshipper.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for dsr_dropshipper.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsr_dropshipper.LAST_UPDATE_DATE
     *
     * @return the value of dsr_dropshipper.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsr_dropshipper.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for dsr_dropshipper.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsr_dropshipper.CALL_CNT
     *
     * @return the value of dsr_dropshipper.CALL_CNT
     *
     * @mbg.generated
     */
    public Integer getCallCnt() {
        return callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsr_dropshipper.CALL_CNT
     *
     * @param callCnt the value for dsr_dropshipper.CALL_CNT
     *
     * @mbg.generated
     */
    public void setCallCnt(Integer callCnt) {
        this.callCnt = callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsr_dropshipper.REMARK
     *
     * @return the value of dsr_dropshipper.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsr_dropshipper.REMARK
     *
     * @param remark the value for dsr_dropshipper.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsr_dropshipper.STS_CD
     *
     * @return the value of dsr_dropshipper.STS_CD
     *
     * @mbg.generated
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsr_dropshipper.STS_CD
     *
     * @param stsCd the value for dsr_dropshipper.STS_CD
     *
     * @mbg.generated
     */
    public void setStsCd(String stsCd) {
        this.stsCd = stsCd == null ? null : stsCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsr_dropshipper.REGISTER_DATE
     *
     * @return the value of dsr_dropshipper.REGISTER_DATE
     *
     * @mbg.generated
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsr_dropshipper.REGISTER_DATE
     *
     * @param registerDate the value for dsr_dropshipper.REGISTER_DATE
     *
     * @mbg.generated
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }
}