package com.neusoft.bsp.model;

import java.util.Date;

public class dropshipPrice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drp_dropship_price.DRP_ID
     *
     * @mbg.generated
     */
    private Integer drpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drp_dropship_price.OFP_ID
     *
     * @mbg.generated
     */
    private Integer ofpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drp_dropship_price.DSR_ID
     *
     * @mbg.generated
     */
    private Integer dsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drp_dropship_price.WAR_ID
     *
     * @mbg.generated
     */
    private Integer warId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drp_dropship_price.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drp_dropship_price.CREATION_DATE
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drp_dropship_price.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drp_dropship_price.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drp_dropship_price.CALL_CNT
     *
     * @mbg.generated
     */
    private Integer callCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drp_dropship_price.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drp_dropship_price.STS_CD
     *
     * @mbg.generated
     */
    private String stsCd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drp_dropship_price
     *
     * @mbg.generated
     */
    public dropshipPrice(Integer drpId, Integer ofpId, Integer dsrId, Integer warId, String createdBy, Date creationDate, String lastUpdateBy, Date lastUpdateDate, Integer callCnt, String remark, String stsCd) {
        this.drpId = drpId;
        this.ofpId = ofpId;
        this.dsrId = dsrId;
        this.warId = warId;
        this.createdBy = createdBy;
        this.creationDate = creationDate;
        this.lastUpdateBy = lastUpdateBy;
        this.lastUpdateDate = lastUpdateDate;
        this.callCnt = callCnt;
        this.remark = remark;
        this.stsCd = stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drp_dropship_price
     *
     * @mbg.generated
     */
    public dropshipPrice() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drp_dropship_price.DRP_ID
     *
     * @return the value of drp_dropship_price.DRP_ID
     *
     * @mbg.generated
     */
    public Integer getDrpId() {
        return drpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drp_dropship_price.DRP_ID
     *
     * @param drpId the value for drp_dropship_price.DRP_ID
     *
     * @mbg.generated
     */
    public void setDrpId(Integer drpId) {
        this.drpId = drpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drp_dropship_price.OFP_ID
     *
     * @return the value of drp_dropship_price.OFP_ID
     *
     * @mbg.generated
     */
    public Integer getOfpId() {
        return ofpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drp_dropship_price.OFP_ID
     *
     * @param ofpId the value for drp_dropship_price.OFP_ID
     *
     * @mbg.generated
     */
    public void setOfpId(Integer ofpId) {
        this.ofpId = ofpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drp_dropship_price.DSR_ID
     *
     * @return the value of drp_dropship_price.DSR_ID
     *
     * @mbg.generated
     */
    public Integer getDsrId() {
        return dsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drp_dropship_price.DSR_ID
     *
     * @param dsrId the value for drp_dropship_price.DSR_ID
     *
     * @mbg.generated
     */
    public void setDsrId(Integer dsrId) {
        this.dsrId = dsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drp_dropship_price.WAR_ID
     *
     * @return the value of drp_dropship_price.WAR_ID
     *
     * @mbg.generated
     */
    public Integer getWarId() {
        return warId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drp_dropship_price.WAR_ID
     *
     * @param warId the value for drp_dropship_price.WAR_ID
     *
     * @mbg.generated
     */
    public void setWarId(Integer warId) {
        this.warId = warId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drp_dropship_price.CREATED_BY
     *
     * @return the value of drp_dropship_price.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drp_dropship_price.CREATED_BY
     *
     * @param createdBy the value for drp_dropship_price.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drp_dropship_price.CREATION_DATE
     *
     * @return the value of drp_dropship_price.CREATION_DATE
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drp_dropship_price.CREATION_DATE
     *
     * @param creationDate the value for drp_dropship_price.CREATION_DATE
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drp_dropship_price.LAST_UPDATE_BY
     *
     * @return the value of drp_dropship_price.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drp_dropship_price.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for drp_dropship_price.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drp_dropship_price.LAST_UPDATE_DATE
     *
     * @return the value of drp_dropship_price.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drp_dropship_price.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for drp_dropship_price.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drp_dropship_price.CALL_CNT
     *
     * @return the value of drp_dropship_price.CALL_CNT
     *
     * @mbg.generated
     */
    public Integer getCallCnt() {
        return callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drp_dropship_price.CALL_CNT
     *
     * @param callCnt the value for drp_dropship_price.CALL_CNT
     *
     * @mbg.generated
     */
    public void setCallCnt(Integer callCnt) {
        this.callCnt = callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drp_dropship_price.REMARK
     *
     * @return the value of drp_dropship_price.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drp_dropship_price.REMARK
     *
     * @param remark the value for drp_dropship_price.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drp_dropship_price.STS_CD
     *
     * @return the value of drp_dropship_price.STS_CD
     *
     * @mbg.generated
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drp_dropship_price.STS_CD
     *
     * @param stsCd the value for drp_dropship_price.STS_CD
     *
     * @mbg.generated
     */
    public void setStsCd(String stsCd) {
        this.stsCd = stsCd == null ? null : stsCd.trim();
    }
}