package com.neusoft.bsp.model;

import java.util.Date;

public class governmentArea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goa_government_area.GOA_ID
     *
     * @mbg.generated
     */
    private Integer goaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goa_government_area.ZIP_CODE
     *
     * @mbg.generated
     */
    private String zipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goa_government_area.STATE
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goa_government_area.STATE_SHORTHAND
     *
     * @mbg.generated
     */
    private String stateShorthand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goa_government_area.CITY
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goa_government_area.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goa_government_area.CREATION_DATE
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goa_government_area.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goa_government_area.CALL_CNT
     *
     * @mbg.generated
     */
    private Integer callCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goa_government_area.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goa_government_area.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goa_government_area.STS_CD
     *
     * @mbg.generated
     */
    private String stsCd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goa_government_area
     *
     * @mbg.generated
     */
    public governmentArea(Integer goaId, String zipCode, String state, String stateShorthand, String city, String createdBy, Date creationDate, String lastUpdateBy, Integer callCnt, Date lastUpdateDate, String remark, String stsCd) {
        this.goaId = goaId;
        this.zipCode = zipCode;
        this.state = state;
        this.stateShorthand = stateShorthand;
        this.city = city;
        this.createdBy = createdBy;
        this.creationDate = creationDate;
        this.lastUpdateBy = lastUpdateBy;
        this.callCnt = callCnt;
        this.lastUpdateDate = lastUpdateDate;
        this.remark = remark;
        this.stsCd = stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goa_government_area
     *
     * @mbg.generated
     */
    public governmentArea() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goa_government_area.GOA_ID
     *
     * @return the value of goa_government_area.GOA_ID
     *
     * @mbg.generated
     */
    public Integer getGoaId() {
        return goaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goa_government_area.GOA_ID
     *
     * @param goaId the value for goa_government_area.GOA_ID
     *
     * @mbg.generated
     */
    public void setGoaId(Integer goaId) {
        this.goaId = goaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goa_government_area.ZIP_CODE
     *
     * @return the value of goa_government_area.ZIP_CODE
     *
     * @mbg.generated
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goa_government_area.ZIP_CODE
     *
     * @param zipCode the value for goa_government_area.ZIP_CODE
     *
     * @mbg.generated
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goa_government_area.STATE
     *
     * @return the value of goa_government_area.STATE
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goa_government_area.STATE
     *
     * @param state the value for goa_government_area.STATE
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goa_government_area.STATE_SHORTHAND
     *
     * @return the value of goa_government_area.STATE_SHORTHAND
     *
     * @mbg.generated
     */
    public String getStateShorthand() {
        return stateShorthand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goa_government_area.STATE_SHORTHAND
     *
     * @param stateShorthand the value for goa_government_area.STATE_SHORTHAND
     *
     * @mbg.generated
     */
    public void setStateShorthand(String stateShorthand) {
        this.stateShorthand = stateShorthand == null ? null : stateShorthand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goa_government_area.CITY
     *
     * @return the value of goa_government_area.CITY
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goa_government_area.CITY
     *
     * @param city the value for goa_government_area.CITY
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goa_government_area.CREATED_BY
     *
     * @return the value of goa_government_area.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goa_government_area.CREATED_BY
     *
     * @param createdBy the value for goa_government_area.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goa_government_area.CREATION_DATE
     *
     * @return the value of goa_government_area.CREATION_DATE
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goa_government_area.CREATION_DATE
     *
     * @param creationDate the value for goa_government_area.CREATION_DATE
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goa_government_area.LAST_UPDATE_BY
     *
     * @return the value of goa_government_area.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goa_government_area.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for goa_government_area.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goa_government_area.CALL_CNT
     *
     * @return the value of goa_government_area.CALL_CNT
     *
     * @mbg.generated
     */
    public Integer getCallCnt() {
        return callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goa_government_area.CALL_CNT
     *
     * @param callCnt the value for goa_government_area.CALL_CNT
     *
     * @mbg.generated
     */
    public void setCallCnt(Integer callCnt) {
        this.callCnt = callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goa_government_area.LAST_UPDATE_DATE
     *
     * @return the value of goa_government_area.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goa_government_area.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for goa_government_area.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goa_government_area.REMARK
     *
     * @return the value of goa_government_area.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goa_government_area.REMARK
     *
     * @param remark the value for goa_government_area.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goa_government_area.STS_CD
     *
     * @return the value of goa_government_area.STS_CD
     *
     * @mbg.generated
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goa_government_area.STS_CD
     *
     * @param stsCd the value for goa_government_area.STS_CD
     *
     * @mbg.generated
     */
    public void setStsCd(String stsCd) {
        this.stsCd = stsCd == null ? null : stsCd.trim();
    }
}