package com.neusoft.bsp.model;

import java.util.Date;

public class monitorResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mor_monitor_result.MOR_ID
     *
     * @mbg.generated
     */
    private Integer morId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mor_monitor_result.CLASS_NAME
     *
     * @mbg.generated
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mor_monitor_result.JSON_STRING
     *
     * @mbg.generated
     */
    private String jsonString;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mor_monitor_result.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mor_monitor_result.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mor_monitor_result.UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mor_monitor_result.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mor_monitor_result.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mor_monitor_result.STS_CD
     *
     * @mbg.generated
     */
    private String stsCd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mor_monitor_result
     *
     * @mbg.generated
     */
    public monitorResult(Integer morId, String className, String jsonString, Date createDate, String createBy, Date updateDate, String updateBy, String remark, String stsCd) {
        this.morId = morId;
        this.className = className;
        this.jsonString = jsonString;
        this.createDate = createDate;
        this.createBy = createBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.remark = remark;
        this.stsCd = stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mor_monitor_result
     *
     * @mbg.generated
     */
    public monitorResult() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mor_monitor_result.MOR_ID
     *
     * @return the value of mor_monitor_result.MOR_ID
     *
     * @mbg.generated
     */
    public Integer getMorId() {
        return morId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mor_monitor_result.MOR_ID
     *
     * @param morId the value for mor_monitor_result.MOR_ID
     *
     * @mbg.generated
     */
    public void setMorId(Integer morId) {
        this.morId = morId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mor_monitor_result.CLASS_NAME
     *
     * @return the value of mor_monitor_result.CLASS_NAME
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mor_monitor_result.CLASS_NAME
     *
     * @param className the value for mor_monitor_result.CLASS_NAME
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mor_monitor_result.JSON_STRING
     *
     * @return the value of mor_monitor_result.JSON_STRING
     *
     * @mbg.generated
     */
    public String getJsonString() {
        return jsonString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mor_monitor_result.JSON_STRING
     *
     * @param jsonString the value for mor_monitor_result.JSON_STRING
     *
     * @mbg.generated
     */
    public void setJsonString(String jsonString) {
        this.jsonString = jsonString == null ? null : jsonString.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mor_monitor_result.CREATE_DATE
     *
     * @return the value of mor_monitor_result.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mor_monitor_result.CREATE_DATE
     *
     * @param createDate the value for mor_monitor_result.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mor_monitor_result.CREATE_BY
     *
     * @return the value of mor_monitor_result.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mor_monitor_result.CREATE_BY
     *
     * @param createBy the value for mor_monitor_result.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mor_monitor_result.UPDATE_DATE
     *
     * @return the value of mor_monitor_result.UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mor_monitor_result.UPDATE_DATE
     *
     * @param updateDate the value for mor_monitor_result.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mor_monitor_result.UPDATE_BY
     *
     * @return the value of mor_monitor_result.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mor_monitor_result.UPDATE_BY
     *
     * @param updateBy the value for mor_monitor_result.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mor_monitor_result.REMARK
     *
     * @return the value of mor_monitor_result.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mor_monitor_result.REMARK
     *
     * @param remark the value for mor_monitor_result.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mor_monitor_result.STS_CD
     *
     * @return the value of mor_monitor_result.STS_CD
     *
     * @mbg.generated
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mor_monitor_result.STS_CD
     *
     * @param stsCd the value for mor_monitor_result.STS_CD
     *
     * @mbg.generated
     */
    public void setStsCd(String stsCd) {
        this.stsCd = stsCd == null ? null : stsCd.trim();
    }
}