package com.neusoft.bsp.model;

import java.math.BigDecimal;
import java.util.Date;

public class offerPrice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ofp_offer_price.OFP_ID
     *
     * @mbg.generated
     */
    private Integer ofpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ofp_offer_price.MAN_ID
     *
     * @mbg.generated
     */
    private Integer manId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ofp_offer_price.EFFETIVE_START_DATE
     *
     * @mbg.generated
     */
    private Date effetiveStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ofp_offer_price.EFFECTIVE_END_DATE
     *
     * @mbg.generated
     */
    private Date effectiveEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ofp_offer_price.PRO_ID
     *
     * @mbg.generated
     */
    private Integer proId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ofp_offer_price.PRICE
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ofp_offer_price.TYPE_CD
     *
     * @mbg.generated
     */
    private String typeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ofp_offer_price.DSR_ID
     *
     * @mbg.generated
     */
    private Integer dsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ofp_offer_price.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ofp_offer_price.CREATION_DATE
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ofp_offer_price.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ofp_offer_price.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ofp_offer_price.CALL_CNT
     *
     * @mbg.generated
     */
    private Integer callCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ofp_offer_price.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ofp_offer_price.STS_CD
     *
     * @mbg.generated
     */
    private String stsCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ofp_offer_price.PERIOD
     *
     * @mbg.generated
     */
    private String period;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ofp_offer_price
     *
     * @mbg.generated
     */
    public offerPrice(Integer ofpId, Integer manId, Date effetiveStartDate, Date effectiveEndDate, Integer proId, BigDecimal price, String typeCd, Integer dsrId, String createdBy, Date creationDate, String lastUpdateBy, Date lastUpdateDate, Integer callCnt, String remark, String stsCd, String period) {
        this.ofpId = ofpId;
        this.manId = manId;
        this.effetiveStartDate = effetiveStartDate;
        this.effectiveEndDate = effectiveEndDate;
        this.proId = proId;
        this.price = price;
        this.typeCd = typeCd;
        this.dsrId = dsrId;
        this.createdBy = createdBy;
        this.creationDate = creationDate;
        this.lastUpdateBy = lastUpdateBy;
        this.lastUpdateDate = lastUpdateDate;
        this.callCnt = callCnt;
        this.remark = remark;
        this.stsCd = stsCd;
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ofp_offer_price
     *
     * @mbg.generated
     */
    public offerPrice() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ofp_offer_price.OFP_ID
     *
     * @return the value of ofp_offer_price.OFP_ID
     *
     * @mbg.generated
     */
    public Integer getOfpId() {
        return ofpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ofp_offer_price.OFP_ID
     *
     * @param ofpId the value for ofp_offer_price.OFP_ID
     *
     * @mbg.generated
     */
    public void setOfpId(Integer ofpId) {
        this.ofpId = ofpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ofp_offer_price.MAN_ID
     *
     * @return the value of ofp_offer_price.MAN_ID
     *
     * @mbg.generated
     */
    public Integer getManId() {
        return manId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ofp_offer_price.MAN_ID
     *
     * @param manId the value for ofp_offer_price.MAN_ID
     *
     * @mbg.generated
     */
    public void setManId(Integer manId) {
        this.manId = manId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ofp_offer_price.EFFETIVE_START_DATE
     *
     * @return the value of ofp_offer_price.EFFETIVE_START_DATE
     *
     * @mbg.generated
     */
    public Date getEffetiveStartDate() {
        return effetiveStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ofp_offer_price.EFFETIVE_START_DATE
     *
     * @param effetiveStartDate the value for ofp_offer_price.EFFETIVE_START_DATE
     *
     * @mbg.generated
     */
    public void setEffetiveStartDate(Date effetiveStartDate) {
        this.effetiveStartDate = effetiveStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ofp_offer_price.EFFECTIVE_END_DATE
     *
     * @return the value of ofp_offer_price.EFFECTIVE_END_DATE
     *
     * @mbg.generated
     */
    public Date getEffectiveEndDate() {
        return effectiveEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ofp_offer_price.EFFECTIVE_END_DATE
     *
     * @param effectiveEndDate the value for ofp_offer_price.EFFECTIVE_END_DATE
     *
     * @mbg.generated
     */
    public void setEffectiveEndDate(Date effectiveEndDate) {
        this.effectiveEndDate = effectiveEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ofp_offer_price.PRO_ID
     *
     * @return the value of ofp_offer_price.PRO_ID
     *
     * @mbg.generated
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ofp_offer_price.PRO_ID
     *
     * @param proId the value for ofp_offer_price.PRO_ID
     *
     * @mbg.generated
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ofp_offer_price.PRICE
     *
     * @return the value of ofp_offer_price.PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ofp_offer_price.PRICE
     *
     * @param price the value for ofp_offer_price.PRICE
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ofp_offer_price.TYPE_CD
     *
     * @return the value of ofp_offer_price.TYPE_CD
     *
     * @mbg.generated
     */
    public String getTypeCd() {
        return typeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ofp_offer_price.TYPE_CD
     *
     * @param typeCd the value for ofp_offer_price.TYPE_CD
     *
     * @mbg.generated
     */
    public void setTypeCd(String typeCd) {
        this.typeCd = typeCd == null ? null : typeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ofp_offer_price.DSR_ID
     *
     * @return the value of ofp_offer_price.DSR_ID
     *
     * @mbg.generated
     */
    public Integer getDsrId() {
        return dsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ofp_offer_price.DSR_ID
     *
     * @param dsrId the value for ofp_offer_price.DSR_ID
     *
     * @mbg.generated
     */
    public void setDsrId(Integer dsrId) {
        this.dsrId = dsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ofp_offer_price.CREATED_BY
     *
     * @return the value of ofp_offer_price.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ofp_offer_price.CREATED_BY
     *
     * @param createdBy the value for ofp_offer_price.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ofp_offer_price.CREATION_DATE
     *
     * @return the value of ofp_offer_price.CREATION_DATE
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ofp_offer_price.CREATION_DATE
     *
     * @param creationDate the value for ofp_offer_price.CREATION_DATE
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ofp_offer_price.LAST_UPDATE_BY
     *
     * @return the value of ofp_offer_price.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ofp_offer_price.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for ofp_offer_price.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ofp_offer_price.LAST_UPDATE_DATE
     *
     * @return the value of ofp_offer_price.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ofp_offer_price.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for ofp_offer_price.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ofp_offer_price.CALL_CNT
     *
     * @return the value of ofp_offer_price.CALL_CNT
     *
     * @mbg.generated
     */
    public Integer getCallCnt() {
        return callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ofp_offer_price.CALL_CNT
     *
     * @param callCnt the value for ofp_offer_price.CALL_CNT
     *
     * @mbg.generated
     */
    public void setCallCnt(Integer callCnt) {
        this.callCnt = callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ofp_offer_price.REMARK
     *
     * @return the value of ofp_offer_price.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ofp_offer_price.REMARK
     *
     * @param remark the value for ofp_offer_price.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ofp_offer_price.STS_CD
     *
     * @return the value of ofp_offer_price.STS_CD
     *
     * @mbg.generated
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ofp_offer_price.STS_CD
     *
     * @param stsCd the value for ofp_offer_price.STS_CD
     *
     * @mbg.generated
     */
    public void setStsCd(String stsCd) {
        this.stsCd = stsCd == null ? null : stsCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ofp_offer_price.PERIOD
     *
     * @return the value of ofp_offer_price.PERIOD
     *
     * @mbg.generated
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ofp_offer_price.PERIOD
     *
     * @param period the value for ofp_offer_price.PERIOD
     *
     * @mbg.generated
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }
}