package com.neusoft.bsp.model;

import java.util.Date;

public class parameter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_parameter.PAR_ID
     *
     * @mbg.generated
     */
    private Integer parId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_parameter.PARAM_CD
     *
     * @mbg.generated
     */
    private String paramCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_parameter.PARAM_VALUE
     *
     * @mbg.generated
     */
    private String paramValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_parameter.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_parameter.CREATION_DATE
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_parameter.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_parameter.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_parameter.CALL_CNT
     *
     * @mbg.generated
     */
    private Integer callCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_parameter.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_parameter.STS_CD
     *
     * @mbg.generated
     */
    private String stsCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_parameter.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table par_parameter
     *
     * @mbg.generated
     */
    public parameter(Integer parId, String paramCd, String paramValue, String createdBy, Date creationDate, String lastUpdateBy, Date lastUpdateDate, Integer callCnt, String remark, String stsCd, String description) {
        this.parId = parId;
        this.paramCd = paramCd;
        this.paramValue = paramValue;
        this.createdBy = createdBy;
        this.creationDate = creationDate;
        this.lastUpdateBy = lastUpdateBy;
        this.lastUpdateDate = lastUpdateDate;
        this.callCnt = callCnt;
        this.remark = remark;
        this.stsCd = stsCd;
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table par_parameter
     *
     * @mbg.generated
     */
    public parameter() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_parameter.PAR_ID
     *
     * @return the value of par_parameter.PAR_ID
     *
     * @mbg.generated
     */
    public Integer getParId() {
        return parId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_parameter.PAR_ID
     *
     * @param parId the value for par_parameter.PAR_ID
     *
     * @mbg.generated
     */
    public void setParId(Integer parId) {
        this.parId = parId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_parameter.PARAM_CD
     *
     * @return the value of par_parameter.PARAM_CD
     *
     * @mbg.generated
     */
    public String getParamCd() {
        return paramCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_parameter.PARAM_CD
     *
     * @param paramCd the value for par_parameter.PARAM_CD
     *
     * @mbg.generated
     */
    public void setParamCd(String paramCd) {
        this.paramCd = paramCd == null ? null : paramCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_parameter.PARAM_VALUE
     *
     * @return the value of par_parameter.PARAM_VALUE
     *
     * @mbg.generated
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_parameter.PARAM_VALUE
     *
     * @param paramValue the value for par_parameter.PARAM_VALUE
     *
     * @mbg.generated
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue == null ? null : paramValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_parameter.CREATED_BY
     *
     * @return the value of par_parameter.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_parameter.CREATED_BY
     *
     * @param createdBy the value for par_parameter.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_parameter.CREATION_DATE
     *
     * @return the value of par_parameter.CREATION_DATE
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_parameter.CREATION_DATE
     *
     * @param creationDate the value for par_parameter.CREATION_DATE
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_parameter.LAST_UPDATE_BY
     *
     * @return the value of par_parameter.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_parameter.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for par_parameter.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_parameter.LAST_UPDATE_DATE
     *
     * @return the value of par_parameter.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_parameter.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for par_parameter.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_parameter.CALL_CNT
     *
     * @return the value of par_parameter.CALL_CNT
     *
     * @mbg.generated
     */
    public Integer getCallCnt() {
        return callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_parameter.CALL_CNT
     *
     * @param callCnt the value for par_parameter.CALL_CNT
     *
     * @mbg.generated
     */
    public void setCallCnt(Integer callCnt) {
        this.callCnt = callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_parameter.REMARK
     *
     * @return the value of par_parameter.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_parameter.REMARK
     *
     * @param remark the value for par_parameter.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_parameter.STS_CD
     *
     * @return the value of par_parameter.STS_CD
     *
     * @mbg.generated
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_parameter.STS_CD
     *
     * @param stsCd the value for par_parameter.STS_CD
     *
     * @mbg.generated
     */
    public void setStsCd(String stsCd) {
        this.stsCd = stsCd == null ? null : stsCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_parameter.DESCRIPTION
     *
     * @return the value of par_parameter.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_parameter.DESCRIPTION
     *
     * @param description the value for par_parameter.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}