package com.neusoft.bsp.model;

import java.math.BigDecimal;
import java.util.Date;

public class product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.PRO_ID
     *
     * @mbg.generated
     */
    private Integer proId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.SKU_CD
     *
     * @mbg.generated
     */
    private String skuCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.BRD_ID
     *
     * @mbg.generated
     */
    private Integer brdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.MAN_ID
     *
     * @mbg.generated
     */
    private Integer manId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.TITLE
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.UPC
     *
     * @mbg.generated
     */
    private String upc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.EAN
     *
     * @mbg.generated
     */
    private String ean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.MODEL
     *
     * @mbg.generated
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.WARRANTY_DAY
     *
     * @mbg.generated
     */
    private String warrantyDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.RETAIL_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal retailPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.CREATION_DATE
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.CALL_CNT
     *
     * @mbg.generated
     */
    private Integer callCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.STS_CD
     *
     * @mbg.generated
     */
    private String stsCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.MININUM_RETAIL_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal mininumRetailPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.REPLENISHMENT_PERIOD
     *
     * @mbg.generated
     */
    private Integer replenishmentPeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.KEY_WORDS
     *
     * @mbg.generated
     */
    private String keyWords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.TIME_UNIT
     *
     * @mbg.generated
     */
    private String timeUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.STOCKSETING
     *
     * @mbg.generated
     */
    private Integer stockseting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.WARRANTY
     *
     * @mbg.generated
     */
    private String warranty;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product
     *
     * @mbg.generated
     */
    public product(Integer proId, String skuCd, Integer brdId, Integer manId, String title, String upc, String ean, String model, String warrantyDay, BigDecimal retailPrice, String createdBy, Date creationDate, String lastUpdateBy, Date lastUpdateDate, Integer callCnt, String remark, String stsCd, BigDecimal mininumRetailPrice, Integer replenishmentPeriod, String keyWords, String timeUnit, Integer stockseting, String warranty) {
        this.proId = proId;
        this.skuCd = skuCd;
        this.brdId = brdId;
        this.manId = manId;
        this.title = title;
        this.upc = upc;
        this.ean = ean;
        this.model = model;
        this.warrantyDay = warrantyDay;
        this.retailPrice = retailPrice;
        this.createdBy = createdBy;
        this.creationDate = creationDate;
        this.lastUpdateBy = lastUpdateBy;
        this.lastUpdateDate = lastUpdateDate;
        this.callCnt = callCnt;
        this.remark = remark;
        this.stsCd = stsCd;
        this.mininumRetailPrice = mininumRetailPrice;
        this.replenishmentPeriod = replenishmentPeriod;
        this.keyWords = keyWords;
        this.timeUnit = timeUnit;
        this.stockseting = stockseting;
        this.warranty = warranty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product
     *
     * @mbg.generated
     */
    public product() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.PRO_ID
     *
     * @return the value of pro_product.PRO_ID
     *
     * @mbg.generated
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.PRO_ID
     *
     * @param proId the value for pro_product.PRO_ID
     *
     * @mbg.generated
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.SKU_CD
     *
     * @return the value of pro_product.SKU_CD
     *
     * @mbg.generated
     */
    public String getSkuCd() {
        return skuCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.SKU_CD
     *
     * @param skuCd the value for pro_product.SKU_CD
     *
     * @mbg.generated
     */
    public void setSkuCd(String skuCd) {
        this.skuCd = skuCd == null ? null : skuCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.BRD_ID
     *
     * @return the value of pro_product.BRD_ID
     *
     * @mbg.generated
     */
    public Integer getBrdId() {
        return brdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.BRD_ID
     *
     * @param brdId the value for pro_product.BRD_ID
     *
     * @mbg.generated
     */
    public void setBrdId(Integer brdId) {
        this.brdId = brdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.MAN_ID
     *
     * @return the value of pro_product.MAN_ID
     *
     * @mbg.generated
     */
    public Integer getManId() {
        return manId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.MAN_ID
     *
     * @param manId the value for pro_product.MAN_ID
     *
     * @mbg.generated
     */
    public void setManId(Integer manId) {
        this.manId = manId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.TITLE
     *
     * @return the value of pro_product.TITLE
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.TITLE
     *
     * @param title the value for pro_product.TITLE
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.UPC
     *
     * @return the value of pro_product.UPC
     *
     * @mbg.generated
     */
    public String getUpc() {
        return upc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.UPC
     *
     * @param upc the value for pro_product.UPC
     *
     * @mbg.generated
     */
    public void setUpc(String upc) {
        this.upc = upc == null ? null : upc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.EAN
     *
     * @return the value of pro_product.EAN
     *
     * @mbg.generated
     */
    public String getEan() {
        return ean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.EAN
     *
     * @param ean the value for pro_product.EAN
     *
     * @mbg.generated
     */
    public void setEan(String ean) {
        this.ean = ean == null ? null : ean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.MODEL
     *
     * @return the value of pro_product.MODEL
     *
     * @mbg.generated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.MODEL
     *
     * @param model the value for pro_product.MODEL
     *
     * @mbg.generated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.WARRANTY_DAY
     *
     * @return the value of pro_product.WARRANTY_DAY
     *
     * @mbg.generated
     */
    public String getWarrantyDay() {
        return warrantyDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.WARRANTY_DAY
     *
     * @param warrantyDay the value for pro_product.WARRANTY_DAY
     *
     * @mbg.generated
     */
    public void setWarrantyDay(String warrantyDay) {
        this.warrantyDay = warrantyDay == null ? null : warrantyDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.RETAIL_PRICE
     *
     * @return the value of pro_product.RETAIL_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getRetailPrice() {
        return retailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.RETAIL_PRICE
     *
     * @param retailPrice the value for pro_product.RETAIL_PRICE
     *
     * @mbg.generated
     */
    public void setRetailPrice(BigDecimal retailPrice) {
        this.retailPrice = retailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.CREATED_BY
     *
     * @return the value of pro_product.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.CREATED_BY
     *
     * @param createdBy the value for pro_product.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.CREATION_DATE
     *
     * @return the value of pro_product.CREATION_DATE
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.CREATION_DATE
     *
     * @param creationDate the value for pro_product.CREATION_DATE
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.LAST_UPDATE_BY
     *
     * @return the value of pro_product.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for pro_product.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.LAST_UPDATE_DATE
     *
     * @return the value of pro_product.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for pro_product.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.CALL_CNT
     *
     * @return the value of pro_product.CALL_CNT
     *
     * @mbg.generated
     */
    public Integer getCallCnt() {
        return callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.CALL_CNT
     *
     * @param callCnt the value for pro_product.CALL_CNT
     *
     * @mbg.generated
     */
    public void setCallCnt(Integer callCnt) {
        this.callCnt = callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.REMARK
     *
     * @return the value of pro_product.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.REMARK
     *
     * @param remark the value for pro_product.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.STS_CD
     *
     * @return the value of pro_product.STS_CD
     *
     * @mbg.generated
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.STS_CD
     *
     * @param stsCd the value for pro_product.STS_CD
     *
     * @mbg.generated
     */
    public void setStsCd(String stsCd) {
        this.stsCd = stsCd == null ? null : stsCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.MININUM_RETAIL_PRICE
     *
     * @return the value of pro_product.MININUM_RETAIL_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getMininumRetailPrice() {
        return mininumRetailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.MININUM_RETAIL_PRICE
     *
     * @param mininumRetailPrice the value for pro_product.MININUM_RETAIL_PRICE
     *
     * @mbg.generated
     */
    public void setMininumRetailPrice(BigDecimal mininumRetailPrice) {
        this.mininumRetailPrice = mininumRetailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.REPLENISHMENT_PERIOD
     *
     * @return the value of pro_product.REPLENISHMENT_PERIOD
     *
     * @mbg.generated
     */
    public Integer getReplenishmentPeriod() {
        return replenishmentPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.REPLENISHMENT_PERIOD
     *
     * @param replenishmentPeriod the value for pro_product.REPLENISHMENT_PERIOD
     *
     * @mbg.generated
     */
    public void setReplenishmentPeriod(Integer replenishmentPeriod) {
        this.replenishmentPeriod = replenishmentPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.KEY_WORDS
     *
     * @return the value of pro_product.KEY_WORDS
     *
     * @mbg.generated
     */
    public String getKeyWords() {
        return keyWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.KEY_WORDS
     *
     * @param keyWords the value for pro_product.KEY_WORDS
     *
     * @mbg.generated
     */
    public void setKeyWords(String keyWords) {
        this.keyWords = keyWords == null ? null : keyWords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.TIME_UNIT
     *
     * @return the value of pro_product.TIME_UNIT
     *
     * @mbg.generated
     */
    public String getTimeUnit() {
        return timeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.TIME_UNIT
     *
     * @param timeUnit the value for pro_product.TIME_UNIT
     *
     * @mbg.generated
     */
    public void setTimeUnit(String timeUnit) {
        this.timeUnit = timeUnit == null ? null : timeUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.STOCKSETING
     *
     * @return the value of pro_product.STOCKSETING
     *
     * @mbg.generated
     */
    public Integer getStockseting() {
        return stockseting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.STOCKSETING
     *
     * @param stockseting the value for pro_product.STOCKSETING
     *
     * @mbg.generated
     */
    public void setStockseting(Integer stockseting) {
        this.stockseting = stockseting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.WARRANTY
     *
     * @return the value of pro_product.WARRANTY
     *
     * @mbg.generated
     */
    public String getWarranty() {
        return warranty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.WARRANTY
     *
     * @param warranty the value for pro_product.WARRANTY
     *
     * @mbg.generated
     */
    public void setWarranty(String warranty) {
        this.warranty = warranty == null ? null : warranty.trim();
    }
}