package com.neusoft.bsp.model;

import java.util.Date;

public class productDescrition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdn_product_descrition.PDN_ID
     *
     * @mbg.generated
     */
    private Integer pdnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdn_product_descrition.PRO_ID
     *
     * @mbg.generated
     */
    private Integer proId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdn_product_descrition.TYPE_CD
     *
     * @mbg.generated
     */
    private String typeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdn_product_descrition.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdn_product_descrition.CREATION_DATE
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdn_product_descrition.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdn_product_descrition.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdn_product_descrition.CALL_CNT
     *
     * @mbg.generated
     */
    private Integer callCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdn_product_descrition.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdn_product_descrition.STS_CD
     *
     * @mbg.generated
     */
    private String stsCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdn_product_descrition.DESCRITION
     *
     * @mbg.generated
     */
    private String descrition;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdn_product_descrition
     *
     * @mbg.generated
     */
    public productDescrition(Integer pdnId, Integer proId, String typeCd, String createdBy, Date creationDate, String lastUpdateBy, Date lastUpdateDate, Integer callCnt, String remark, String stsCd, String descrition) {
        this.pdnId = pdnId;
        this.proId = proId;
        this.typeCd = typeCd;
        this.createdBy = createdBy;
        this.creationDate = creationDate;
        this.lastUpdateBy = lastUpdateBy;
        this.lastUpdateDate = lastUpdateDate;
        this.callCnt = callCnt;
        this.remark = remark;
        this.stsCd = stsCd;
        this.descrition = descrition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdn_product_descrition
     *
     * @mbg.generated
     */
    public productDescrition() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdn_product_descrition.PDN_ID
     *
     * @return the value of pdn_product_descrition.PDN_ID
     *
     * @mbg.generated
     */
    public Integer getPdnId() {
        return pdnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdn_product_descrition.PDN_ID
     *
     * @param pdnId the value for pdn_product_descrition.PDN_ID
     *
     * @mbg.generated
     */
    public void setPdnId(Integer pdnId) {
        this.pdnId = pdnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdn_product_descrition.PRO_ID
     *
     * @return the value of pdn_product_descrition.PRO_ID
     *
     * @mbg.generated
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdn_product_descrition.PRO_ID
     *
     * @param proId the value for pdn_product_descrition.PRO_ID
     *
     * @mbg.generated
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdn_product_descrition.TYPE_CD
     *
     * @return the value of pdn_product_descrition.TYPE_CD
     *
     * @mbg.generated
     */
    public String getTypeCd() {
        return typeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdn_product_descrition.TYPE_CD
     *
     * @param typeCd the value for pdn_product_descrition.TYPE_CD
     *
     * @mbg.generated
     */
    public void setTypeCd(String typeCd) {
        this.typeCd = typeCd == null ? null : typeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdn_product_descrition.CREATED_BY
     *
     * @return the value of pdn_product_descrition.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdn_product_descrition.CREATED_BY
     *
     * @param createdBy the value for pdn_product_descrition.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdn_product_descrition.CREATION_DATE
     *
     * @return the value of pdn_product_descrition.CREATION_DATE
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdn_product_descrition.CREATION_DATE
     *
     * @param creationDate the value for pdn_product_descrition.CREATION_DATE
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdn_product_descrition.LAST_UPDATE_BY
     *
     * @return the value of pdn_product_descrition.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdn_product_descrition.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for pdn_product_descrition.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdn_product_descrition.LAST_UPDATE_DATE
     *
     * @return the value of pdn_product_descrition.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdn_product_descrition.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for pdn_product_descrition.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdn_product_descrition.CALL_CNT
     *
     * @return the value of pdn_product_descrition.CALL_CNT
     *
     * @mbg.generated
     */
    public Integer getCallCnt() {
        return callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdn_product_descrition.CALL_CNT
     *
     * @param callCnt the value for pdn_product_descrition.CALL_CNT
     *
     * @mbg.generated
     */
    public void setCallCnt(Integer callCnt) {
        this.callCnt = callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdn_product_descrition.REMARK
     *
     * @return the value of pdn_product_descrition.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdn_product_descrition.REMARK
     *
     * @param remark the value for pdn_product_descrition.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdn_product_descrition.STS_CD
     *
     * @return the value of pdn_product_descrition.STS_CD
     *
     * @mbg.generated
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdn_product_descrition.STS_CD
     *
     * @param stsCd the value for pdn_product_descrition.STS_CD
     *
     * @mbg.generated
     */
    public void setStsCd(String stsCd) {
        this.stsCd = stsCd == null ? null : stsCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdn_product_descrition.DESCRITION
     *
     * @return the value of pdn_product_descrition.DESCRITION
     *
     * @mbg.generated
     */
    public String getDescrition() {
        return descrition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdn_product_descrition.DESCRITION
     *
     * @param descrition the value for pdn_product_descrition.DESCRITION
     *
     * @mbg.generated
     */
    public void setDescrition(String descrition) {
        this.descrition = descrition == null ? null : descrition.trim();
    }
}