package com.neusoft.bsp.model;

import java.util.Date;

public class productCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prc_product_category.PRC_ID
     *
     * @mbg.generated
     */
    private Integer prcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prc_product_category.PRO_ID
     *
     * @mbg.generated
     */
    private Integer proId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prc_product_category.CATEGORY_ID
     *
     * @mbg.generated
     */
    private String categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prc_product_category.CATEGORY_NAME
     *
     * @mbg.generated
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prc_product_category.CATEGORY_PATH
     *
     * @mbg.generated
     */
    private String categoryPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prc_product_category.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prc_product_category.CREATION_DATE
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prc_product_category.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prc_product_category.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prc_product_category.CALL_CNT
     *
     * @mbg.generated
     */
    private Integer callCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prc_product_category.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prc_product_category.STS_CD
     *
     * @mbg.generated
     */
    private String stsCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prc_product_category.PLATEFORM_TYPE
     *
     * @mbg.generated
     */
    private String plateformType;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    public productCategory(Integer prcId, Integer proId, String categoryId, String categoryName, String categoryPath, String createdBy, Date creationDate, String lastUpdateBy, Date lastUpdateDate, Integer callCnt, String remark, String stsCd, String plateformType) {
        this.prcId = prcId;
        this.proId = proId;
        this.categoryId = categoryId;
        this.categoryName = categoryName;
        this.categoryPath = categoryPath;
        this.createdBy = createdBy;
        this.creationDate = creationDate;
        this.lastUpdateBy = lastUpdateBy;
        this.lastUpdateDate = lastUpdateDate;
        this.callCnt = callCnt;
        this.remark = remark;
        this.stsCd = stsCd;
        this.plateformType = plateformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    public productCategory() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prc_product_category.PRC_ID
     *
     * @return the value of prc_product_category.PRC_ID
     *
     * @mbg.generated
     */
    public Integer getPrcId() {
        return prcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prc_product_category.PRC_ID
     *
     * @param prcId the value for prc_product_category.PRC_ID
     *
     * @mbg.generated
     */
    public void setPrcId(Integer prcId) {
        this.prcId = prcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prc_product_category.PRO_ID
     *
     * @return the value of prc_product_category.PRO_ID
     *
     * @mbg.generated
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prc_product_category.PRO_ID
     *
     * @param proId the value for prc_product_category.PRO_ID
     *
     * @mbg.generated
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prc_product_category.CATEGORY_ID
     *
     * @return the value of prc_product_category.CATEGORY_ID
     *
     * @mbg.generated
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prc_product_category.CATEGORY_ID
     *
     * @param categoryId the value for prc_product_category.CATEGORY_ID
     *
     * @mbg.generated
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prc_product_category.CATEGORY_NAME
     *
     * @return the value of prc_product_category.CATEGORY_NAME
     *
     * @mbg.generated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prc_product_category.CATEGORY_NAME
     *
     * @param categoryName the value for prc_product_category.CATEGORY_NAME
     *
     * @mbg.generated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prc_product_category.CATEGORY_PATH
     *
     * @return the value of prc_product_category.CATEGORY_PATH
     *
     * @mbg.generated
     */
    public String getCategoryPath() {
        return categoryPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prc_product_category.CATEGORY_PATH
     *
     * @param categoryPath the value for prc_product_category.CATEGORY_PATH
     *
     * @mbg.generated
     */
    public void setCategoryPath(String categoryPath) {
        this.categoryPath = categoryPath == null ? null : categoryPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prc_product_category.CREATED_BY
     *
     * @return the value of prc_product_category.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prc_product_category.CREATED_BY
     *
     * @param createdBy the value for prc_product_category.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prc_product_category.CREATION_DATE
     *
     * @return the value of prc_product_category.CREATION_DATE
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prc_product_category.CREATION_DATE
     *
     * @param creationDate the value for prc_product_category.CREATION_DATE
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prc_product_category.LAST_UPDATE_BY
     *
     * @return the value of prc_product_category.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prc_product_category.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for prc_product_category.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prc_product_category.LAST_UPDATE_DATE
     *
     * @return the value of prc_product_category.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prc_product_category.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for prc_product_category.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prc_product_category.CALL_CNT
     *
     * @return the value of prc_product_category.CALL_CNT
     *
     * @mbg.generated
     */
    public Integer getCallCnt() {
        return callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prc_product_category.CALL_CNT
     *
     * @param callCnt the value for prc_product_category.CALL_CNT
     *
     * @mbg.generated
     */
    public void setCallCnt(Integer callCnt) {
        this.callCnt = callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prc_product_category.REMARK
     *
     * @return the value of prc_product_category.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prc_product_category.REMARK
     *
     * @param remark the value for prc_product_category.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prc_product_category.STS_CD
     *
     * @return the value of prc_product_category.STS_CD
     *
     * @mbg.generated
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prc_product_category.STS_CD
     *
     * @param stsCd the value for prc_product_category.STS_CD
     *
     * @mbg.generated
     */
    public void setStsCd(String stsCd) {
        this.stsCd = stsCd == null ? null : stsCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prc_product_category.PLATEFORM_TYPE
     *
     * @return the value of prc_product_category.PLATEFORM_TYPE
     *
     * @mbg.generated
     */
    public String getPlateformType() {
        return plateformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prc_product_category.PLATEFORM_TYPE
     *
     * @param plateformType the value for prc_product_category.PLATEFORM_TYPE
     *
     * @mbg.generated
     */
    public void setPlateformType(String plateformType) {
        this.plateformType = plateformType == null ? null : plateformType.trim();
    }
}