package com.neusoft.bsp.model;

import java.math.BigDecimal;
import java.util.Date;

public class salesrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.SAO_ID
     *
     * @mbg.generated
     */
    private Integer saoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.CREATION_DATE
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.CALL_CNT
     *
     * @mbg.generated
     */
    private Integer callCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.STS_CD
     *
     * @mbg.generated
     */
    private String stsCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.MAN_ID
     *
     * @mbg.generated
     */
    private Integer manId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.WAR_ID
     *
     * @mbg.generated
     */
    private Integer warId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.SYNC_DATE
     *
     * @mbg.generated
     */
    private Date syncDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.PAYMENT_DATE
     *
     * @mbg.generated
     */
    private Date paymentDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.PUSH_DATE
     *
     * @mbg.generated
     */
    private Date pushDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.TRACK_NO_DATE
     *
     * @mbg.generated
     */
    private Date trackNoDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.FULFILLMENT_DATE
     *
     * @mbg.generated
     */
    private Date fulfillmentDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.SETTLEMENT_DATE
     *
     * @mbg.generated
     */
    private Date settlementDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.PRODUCT_AMOUNT
     *
     * @mbg.generated
     */
    private BigDecimal productAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.FREIGHT_COST
     *
     * @mbg.generated
     */
    private BigDecimal freightCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.HANDLING_FEE
     *
     * @mbg.generated
     */
    private BigDecimal handlingFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.CUSTOMER_REMARK
     *
     * @mbg.generated
     */
    private String customerRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.ORDER_NO
     *
     * @mbg.generated
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.ORDER_STS
     *
     * @mbg.generated
     */
    private String orderSts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.REFUND_STS
     *
     * @mbg.generated
     */
    private String refundSts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.DELIVERY_STS
     *
     * @mbg.generated
     */
    private String deliverySts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.STO_ID
     *
     * @mbg.generated
     */
    private Integer stoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.LAST_FREIGHT_COST
     *
     * @mbg.generated
     */
    private BigDecimal lastFreightCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.CANCLE_TIME
     *
     * @mbg.generated
     */
    private Date cancleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.AUTO_PAY_STATUS
     *
     * @mbg.generated
     */
    private String autoPayStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.AUTO_PAY_TIME
     *
     * @mbg.generated
     */
    private String autoPayTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sao_sales_order.BUYER_CHECKOUT_MESSAGE
     *
     * @mbg.generated
     */
    private String buyerCheckoutMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sao_sales_order
     *
     * @mbg.generated
     */
    public salesrder(Integer saoId, String createdBy, Date creationDate, String lastUpdateBy, Date lastUpdateDate, Integer callCnt, String remark, String stsCd, Integer manId, Integer warId, Date syncDate, Date paymentDate, Date pushDate, Date trackNoDate, Date fulfillmentDate, Date settlementDate, BigDecimal productAmount, BigDecimal freightCost, BigDecimal handlingFee, String customerRemark, String orderNo, String orderSts, String refundSts, String deliverySts, Integer stoId, BigDecimal lastFreightCost, Date cancleTime, String autoPayStatus, String autoPayTime, String buyerCheckoutMessage) {
        this.saoId = saoId;
        this.createdBy = createdBy;
        this.creationDate = creationDate;
        this.lastUpdateBy = lastUpdateBy;
        this.lastUpdateDate = lastUpdateDate;
        this.callCnt = callCnt;
        this.remark = remark;
        this.stsCd = stsCd;
        this.manId = manId;
        this.warId = warId;
        this.syncDate = syncDate;
        this.paymentDate = paymentDate;
        this.pushDate = pushDate;
        this.trackNoDate = trackNoDate;
        this.fulfillmentDate = fulfillmentDate;
        this.settlementDate = settlementDate;
        this.productAmount = productAmount;
        this.freightCost = freightCost;
        this.handlingFee = handlingFee;
        this.customerRemark = customerRemark;
        this.orderNo = orderNo;
        this.orderSts = orderSts;
        this.refundSts = refundSts;
        this.deliverySts = deliverySts;
        this.stoId = stoId;
        this.lastFreightCost = lastFreightCost;
        this.cancleTime = cancleTime;
        this.autoPayStatus = autoPayStatus;
        this.autoPayTime = autoPayTime;
        this.buyerCheckoutMessage = buyerCheckoutMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sao_sales_order
     *
     * @mbg.generated
     */
    public salesrder() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.SAO_ID
     *
     * @return the value of sao_sales_order.SAO_ID
     *
     * @mbg.generated
     */
    public Integer getSaoId() {
        return saoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.SAO_ID
     *
     * @param saoId the value for sao_sales_order.SAO_ID
     *
     * @mbg.generated
     */
    public void setSaoId(Integer saoId) {
        this.saoId = saoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.CREATED_BY
     *
     * @return the value of sao_sales_order.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.CREATED_BY
     *
     * @param createdBy the value for sao_sales_order.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.CREATION_DATE
     *
     * @return the value of sao_sales_order.CREATION_DATE
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.CREATION_DATE
     *
     * @param creationDate the value for sao_sales_order.CREATION_DATE
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.LAST_UPDATE_BY
     *
     * @return the value of sao_sales_order.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for sao_sales_order.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.LAST_UPDATE_DATE
     *
     * @return the value of sao_sales_order.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for sao_sales_order.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.CALL_CNT
     *
     * @return the value of sao_sales_order.CALL_CNT
     *
     * @mbg.generated
     */
    public Integer getCallCnt() {
        return callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.CALL_CNT
     *
     * @param callCnt the value for sao_sales_order.CALL_CNT
     *
     * @mbg.generated
     */
    public void setCallCnt(Integer callCnt) {
        this.callCnt = callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.REMARK
     *
     * @return the value of sao_sales_order.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.REMARK
     *
     * @param remark the value for sao_sales_order.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.STS_CD
     *
     * @return the value of sao_sales_order.STS_CD
     *
     * @mbg.generated
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.STS_CD
     *
     * @param stsCd the value for sao_sales_order.STS_CD
     *
     * @mbg.generated
     */
    public void setStsCd(String stsCd) {
        this.stsCd = stsCd == null ? null : stsCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.MAN_ID
     *
     * @return the value of sao_sales_order.MAN_ID
     *
     * @mbg.generated
     */
    public Integer getManId() {
        return manId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.MAN_ID
     *
     * @param manId the value for sao_sales_order.MAN_ID
     *
     * @mbg.generated
     */
    public void setManId(Integer manId) {
        this.manId = manId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.WAR_ID
     *
     * @return the value of sao_sales_order.WAR_ID
     *
     * @mbg.generated
     */
    public Integer getWarId() {
        return warId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.WAR_ID
     *
     * @param warId the value for sao_sales_order.WAR_ID
     *
     * @mbg.generated
     */
    public void setWarId(Integer warId) {
        this.warId = warId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.SYNC_DATE
     *
     * @return the value of sao_sales_order.SYNC_DATE
     *
     * @mbg.generated
     */
    public Date getSyncDate() {
        return syncDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.SYNC_DATE
     *
     * @param syncDate the value for sao_sales_order.SYNC_DATE
     *
     * @mbg.generated
     */
    public void setSyncDate(Date syncDate) {
        this.syncDate = syncDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.PAYMENT_DATE
     *
     * @return the value of sao_sales_order.PAYMENT_DATE
     *
     * @mbg.generated
     */
    public Date getPaymentDate() {
        return paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.PAYMENT_DATE
     *
     * @param paymentDate the value for sao_sales_order.PAYMENT_DATE
     *
     * @mbg.generated
     */
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.PUSH_DATE
     *
     * @return the value of sao_sales_order.PUSH_DATE
     *
     * @mbg.generated
     */
    public Date getPushDate() {
        return pushDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.PUSH_DATE
     *
     * @param pushDate the value for sao_sales_order.PUSH_DATE
     *
     * @mbg.generated
     */
    public void setPushDate(Date pushDate) {
        this.pushDate = pushDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.TRACK_NO_DATE
     *
     * @return the value of sao_sales_order.TRACK_NO_DATE
     *
     * @mbg.generated
     */
    public Date getTrackNoDate() {
        return trackNoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.TRACK_NO_DATE
     *
     * @param trackNoDate the value for sao_sales_order.TRACK_NO_DATE
     *
     * @mbg.generated
     */
    public void setTrackNoDate(Date trackNoDate) {
        this.trackNoDate = trackNoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.FULFILLMENT_DATE
     *
     * @return the value of sao_sales_order.FULFILLMENT_DATE
     *
     * @mbg.generated
     */
    public Date getFulfillmentDate() {
        return fulfillmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.FULFILLMENT_DATE
     *
     * @param fulfillmentDate the value for sao_sales_order.FULFILLMENT_DATE
     *
     * @mbg.generated
     */
    public void setFulfillmentDate(Date fulfillmentDate) {
        this.fulfillmentDate = fulfillmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.SETTLEMENT_DATE
     *
     * @return the value of sao_sales_order.SETTLEMENT_DATE
     *
     * @mbg.generated
     */
    public Date getSettlementDate() {
        return settlementDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.SETTLEMENT_DATE
     *
     * @param settlementDate the value for sao_sales_order.SETTLEMENT_DATE
     *
     * @mbg.generated
     */
    public void setSettlementDate(Date settlementDate) {
        this.settlementDate = settlementDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.PRODUCT_AMOUNT
     *
     * @return the value of sao_sales_order.PRODUCT_AMOUNT
     *
     * @mbg.generated
     */
    public BigDecimal getProductAmount() {
        return productAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.PRODUCT_AMOUNT
     *
     * @param productAmount the value for sao_sales_order.PRODUCT_AMOUNT
     *
     * @mbg.generated
     */
    public void setProductAmount(BigDecimal productAmount) {
        this.productAmount = productAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.FREIGHT_COST
     *
     * @return the value of sao_sales_order.FREIGHT_COST
     *
     * @mbg.generated
     */
    public BigDecimal getFreightCost() {
        return freightCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.FREIGHT_COST
     *
     * @param freightCost the value for sao_sales_order.FREIGHT_COST
     *
     * @mbg.generated
     */
    public void setFreightCost(BigDecimal freightCost) {
        this.freightCost = freightCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.HANDLING_FEE
     *
     * @return the value of sao_sales_order.HANDLING_FEE
     *
     * @mbg.generated
     */
    public BigDecimal getHandlingFee() {
        return handlingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.HANDLING_FEE
     *
     * @param handlingFee the value for sao_sales_order.HANDLING_FEE
     *
     * @mbg.generated
     */
    public void setHandlingFee(BigDecimal handlingFee) {
        this.handlingFee = handlingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.CUSTOMER_REMARK
     *
     * @return the value of sao_sales_order.CUSTOMER_REMARK
     *
     * @mbg.generated
     */
    public String getCustomerRemark() {
        return customerRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.CUSTOMER_REMARK
     *
     * @param customerRemark the value for sao_sales_order.CUSTOMER_REMARK
     *
     * @mbg.generated
     */
    public void setCustomerRemark(String customerRemark) {
        this.customerRemark = customerRemark == null ? null : customerRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.ORDER_NO
     *
     * @return the value of sao_sales_order.ORDER_NO
     *
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.ORDER_NO
     *
     * @param orderNo the value for sao_sales_order.ORDER_NO
     *
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.ORDER_STS
     *
     * @return the value of sao_sales_order.ORDER_STS
     *
     * @mbg.generated
     */
    public String getOrderSts() {
        return orderSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.ORDER_STS
     *
     * @param orderSts the value for sao_sales_order.ORDER_STS
     *
     * @mbg.generated
     */
    public void setOrderSts(String orderSts) {
        this.orderSts = orderSts == null ? null : orderSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.REFUND_STS
     *
     * @return the value of sao_sales_order.REFUND_STS
     *
     * @mbg.generated
     */
    public String getRefundSts() {
        return refundSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.REFUND_STS
     *
     * @param refundSts the value for sao_sales_order.REFUND_STS
     *
     * @mbg.generated
     */
    public void setRefundSts(String refundSts) {
        this.refundSts = refundSts == null ? null : refundSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.DELIVERY_STS
     *
     * @return the value of sao_sales_order.DELIVERY_STS
     *
     * @mbg.generated
     */
    public String getDeliverySts() {
        return deliverySts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.DELIVERY_STS
     *
     * @param deliverySts the value for sao_sales_order.DELIVERY_STS
     *
     * @mbg.generated
     */
    public void setDeliverySts(String deliverySts) {
        this.deliverySts = deliverySts == null ? null : deliverySts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.STO_ID
     *
     * @return the value of sao_sales_order.STO_ID
     *
     * @mbg.generated
     */
    public Integer getStoId() {
        return stoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.STO_ID
     *
     * @param stoId the value for sao_sales_order.STO_ID
     *
     * @mbg.generated
     */
    public void setStoId(Integer stoId) {
        this.stoId = stoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.LAST_FREIGHT_COST
     *
     * @return the value of sao_sales_order.LAST_FREIGHT_COST
     *
     * @mbg.generated
     */
    public BigDecimal getLastFreightCost() {
        return lastFreightCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.LAST_FREIGHT_COST
     *
     * @param lastFreightCost the value for sao_sales_order.LAST_FREIGHT_COST
     *
     * @mbg.generated
     */
    public void setLastFreightCost(BigDecimal lastFreightCost) {
        this.lastFreightCost = lastFreightCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.CANCLE_TIME
     *
     * @return the value of sao_sales_order.CANCLE_TIME
     *
     * @mbg.generated
     */
    public Date getCancleTime() {
        return cancleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.CANCLE_TIME
     *
     * @param cancleTime the value for sao_sales_order.CANCLE_TIME
     *
     * @mbg.generated
     */
    public void setCancleTime(Date cancleTime) {
        this.cancleTime = cancleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.AUTO_PAY_STATUS
     *
     * @return the value of sao_sales_order.AUTO_PAY_STATUS
     *
     * @mbg.generated
     */
    public String getAutoPayStatus() {
        return autoPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.AUTO_PAY_STATUS
     *
     * @param autoPayStatus the value for sao_sales_order.AUTO_PAY_STATUS
     *
     * @mbg.generated
     */
    public void setAutoPayStatus(String autoPayStatus) {
        this.autoPayStatus = autoPayStatus == null ? null : autoPayStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.AUTO_PAY_TIME
     *
     * @return the value of sao_sales_order.AUTO_PAY_TIME
     *
     * @mbg.generated
     */
    public String getAutoPayTime() {
        return autoPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.AUTO_PAY_TIME
     *
     * @param autoPayTime the value for sao_sales_order.AUTO_PAY_TIME
     *
     * @mbg.generated
     */
    public void setAutoPayTime(String autoPayTime) {
        this.autoPayTime = autoPayTime == null ? null : autoPayTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sao_sales_order.BUYER_CHECKOUT_MESSAGE
     *
     * @return the value of sao_sales_order.BUYER_CHECKOUT_MESSAGE
     *
     * @mbg.generated
     */
    public String getBuyerCheckoutMessage() {
        return buyerCheckoutMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sao_sales_order.BUYER_CHECKOUT_MESSAGE
     *
     * @param buyerCheckoutMessage the value for sao_sales_order.BUYER_CHECKOUT_MESSAGE
     *
     * @mbg.generated
     */
    public void setBuyerCheckoutMessage(String buyerCheckoutMessage) {
        this.buyerCheckoutMessage = buyerCheckoutMessage == null ? null : buyerCheckoutMessage.trim();
    }
}