package com.neusoft.bsp.model;

public class sequence {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.current_value
     *
     * @mbg.generated
     */
    private Integer currentValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.increment
     *
     * @mbg.generated
     */
    private Integer increment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.initial
     *
     * @mbg.generated
     */
    private String initial;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated
     */
    public sequence(String name, Integer currentValue, Integer increment, String initial) {
        this.name = name;
        this.currentValue = currentValue;
        this.increment = increment;
        this.initial = initial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated
     */
    public sequence() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.name
     *
     * @return the value of sequence.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.name
     *
     * @param name the value for sequence.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.current_value
     *
     * @return the value of sequence.current_value
     *
     * @mbg.generated
     */
    public Integer getCurrentValue() {
        return currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.current_value
     *
     * @param currentValue the value for sequence.current_value
     *
     * @mbg.generated
     */
    public void setCurrentValue(Integer currentValue) {
        this.currentValue = currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.increment
     *
     * @return the value of sequence.increment
     *
     * @mbg.generated
     */
    public Integer getIncrement() {
        return increment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.increment
     *
     * @param increment the value for sequence.increment
     *
     * @mbg.generated
     */
    public void setIncrement(Integer increment) {
        this.increment = increment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.initial
     *
     * @return the value of sequence.initial
     *
     * @mbg.generated
     */
    public String getInitial() {
        return initial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.initial
     *
     * @param initial the value for sequence.initial
     *
     * @mbg.generated
     */
    public void setInitial(String initial) {
        this.initial = initial == null ? null : initial.trim();
    }
}