package com.neusoft.bsp.model;

import java.util.Date;

public class specifiAttribute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spa_specific_attribute.SPA_ID
     *
     * @mbg.generated
     */
    private Integer spaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spa_specific_attribute.PRO_ID
     *
     * @mbg.generated
     */
    private Integer proId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spa_specific_attribute.NAME_EN
     *
     * @mbg.generated
     */
    private String nameEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spa_specific_attribute.NAME_CN
     *
     * @mbg.generated
     */
    private String nameCn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spa_specific_attribute.SEQ_NO
     *
     * @mbg.generated
     */
    private Integer seqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spa_specific_attribute.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spa_specific_attribute.CREATION_DATE
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spa_specific_attribute.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spa_specific_attribute.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spa_specific_attribute.CALL_CNT
     *
     * @mbg.generated
     */
    private Integer callCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spa_specific_attribute.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spa_specific_attribute.STS_CD
     *
     * @mbg.generated
     */
    private String stsCd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spa_specific_attribute
     *
     * @mbg.generated
     */
    public specifiAttribute(Integer spaId, Integer proId, String nameEn, String nameCn, Integer seqNo, String createdBy, Date creationDate, String lastUpdateBy, Date lastUpdateDate, Integer callCnt, String remark, String stsCd) {
        this.spaId = spaId;
        this.proId = proId;
        this.nameEn = nameEn;
        this.nameCn = nameCn;
        this.seqNo = seqNo;
        this.createdBy = createdBy;
        this.creationDate = creationDate;
        this.lastUpdateBy = lastUpdateBy;
        this.lastUpdateDate = lastUpdateDate;
        this.callCnt = callCnt;
        this.remark = remark;
        this.stsCd = stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spa_specific_attribute
     *
     * @mbg.generated
     */
    public specifiAttribute() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spa_specific_attribute.SPA_ID
     *
     * @return the value of spa_specific_attribute.SPA_ID
     *
     * @mbg.generated
     */
    public Integer getSpaId() {
        return spaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spa_specific_attribute.SPA_ID
     *
     * @param spaId the value for spa_specific_attribute.SPA_ID
     *
     * @mbg.generated
     */
    public void setSpaId(Integer spaId) {
        this.spaId = spaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spa_specific_attribute.PRO_ID
     *
     * @return the value of spa_specific_attribute.PRO_ID
     *
     * @mbg.generated
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spa_specific_attribute.PRO_ID
     *
     * @param proId the value for spa_specific_attribute.PRO_ID
     *
     * @mbg.generated
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spa_specific_attribute.NAME_EN
     *
     * @return the value of spa_specific_attribute.NAME_EN
     *
     * @mbg.generated
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spa_specific_attribute.NAME_EN
     *
     * @param nameEn the value for spa_specific_attribute.NAME_EN
     *
     * @mbg.generated
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn == null ? null : nameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spa_specific_attribute.NAME_CN
     *
     * @return the value of spa_specific_attribute.NAME_CN
     *
     * @mbg.generated
     */
    public String getNameCn() {
        return nameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spa_specific_attribute.NAME_CN
     *
     * @param nameCn the value for spa_specific_attribute.NAME_CN
     *
     * @mbg.generated
     */
    public void setNameCn(String nameCn) {
        this.nameCn = nameCn == null ? null : nameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spa_specific_attribute.SEQ_NO
     *
     * @return the value of spa_specific_attribute.SEQ_NO
     *
     * @mbg.generated
     */
    public Integer getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spa_specific_attribute.SEQ_NO
     *
     * @param seqNo the value for spa_specific_attribute.SEQ_NO
     *
     * @mbg.generated
     */
    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spa_specific_attribute.CREATED_BY
     *
     * @return the value of spa_specific_attribute.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spa_specific_attribute.CREATED_BY
     *
     * @param createdBy the value for spa_specific_attribute.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spa_specific_attribute.CREATION_DATE
     *
     * @return the value of spa_specific_attribute.CREATION_DATE
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spa_specific_attribute.CREATION_DATE
     *
     * @param creationDate the value for spa_specific_attribute.CREATION_DATE
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spa_specific_attribute.LAST_UPDATE_BY
     *
     * @return the value of spa_specific_attribute.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spa_specific_attribute.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for spa_specific_attribute.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spa_specific_attribute.LAST_UPDATE_DATE
     *
     * @return the value of spa_specific_attribute.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spa_specific_attribute.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for spa_specific_attribute.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spa_specific_attribute.CALL_CNT
     *
     * @return the value of spa_specific_attribute.CALL_CNT
     *
     * @mbg.generated
     */
    public Integer getCallCnt() {
        return callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spa_specific_attribute.CALL_CNT
     *
     * @param callCnt the value for spa_specific_attribute.CALL_CNT
     *
     * @mbg.generated
     */
    public void setCallCnt(Integer callCnt) {
        this.callCnt = callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spa_specific_attribute.REMARK
     *
     * @return the value of spa_specific_attribute.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spa_specific_attribute.REMARK
     *
     * @param remark the value for spa_specific_attribute.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spa_specific_attribute.STS_CD
     *
     * @return the value of spa_specific_attribute.STS_CD
     *
     * @mbg.generated
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spa_specific_attribute.STS_CD
     *
     * @param stsCd the value for spa_specific_attribute.STS_CD
     *
     * @mbg.generated
     */
    public void setStsCd(String stsCd) {
        this.stsCd = stsCd == null ? null : stsCd.trim();
    }
}