package com.neusoft.bsp.model;

import java.util.Date;

public class store {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column str_store.STR_ID
     *
     * @mbg.generated
     */
    private Integer strId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column str_store.DSR_ID
     *
     * @mbg.generated
     */
    private Integer dsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column str_store.PLATAEFORM_TYPE
     *
     * @mbg.generated
     */
    private String plataeformType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column str_store.STORE_NAME
     *
     * @mbg.generated
     */
    private String storeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column str_store.STORE_STS_CD
     *
     * @mbg.generated
     */
    private String storeStsCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column str_store.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column str_store.CREATION_DATE
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column str_store.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column str_store.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column str_store.CALL_CNT
     *
     * @mbg.generated
     */
    private Integer callCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column str_store.STS_CD
     *
     * @mbg.generated
     */
    private String stsCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column str_store.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table str_store
     *
     * @mbg.generated
     */
    public store(Integer strId, Integer dsrId, String plataeformType, String storeName, String storeStsCd, String createdBy, Date creationDate, String lastUpdateBy, Date lastUpdateDate, Integer callCnt, String stsCd, String remark) {
        this.strId = strId;
        this.dsrId = dsrId;
        this.plataeformType = plataeformType;
        this.storeName = storeName;
        this.storeStsCd = storeStsCd;
        this.createdBy = createdBy;
        this.creationDate = creationDate;
        this.lastUpdateBy = lastUpdateBy;
        this.lastUpdateDate = lastUpdateDate;
        this.callCnt = callCnt;
        this.stsCd = stsCd;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table str_store
     *
     * @mbg.generated
     */
    public store() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column str_store.STR_ID
     *
     * @return the value of str_store.STR_ID
     *
     * @mbg.generated
     */
    public Integer getStrId() {
        return strId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column str_store.STR_ID
     *
     * @param strId the value for str_store.STR_ID
     *
     * @mbg.generated
     */
    public void setStrId(Integer strId) {
        this.strId = strId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column str_store.DSR_ID
     *
     * @return the value of str_store.DSR_ID
     *
     * @mbg.generated
     */
    public Integer getDsrId() {
        return dsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column str_store.DSR_ID
     *
     * @param dsrId the value for str_store.DSR_ID
     *
     * @mbg.generated
     */
    public void setDsrId(Integer dsrId) {
        this.dsrId = dsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column str_store.PLATAEFORM_TYPE
     *
     * @return the value of str_store.PLATAEFORM_TYPE
     *
     * @mbg.generated
     */
    public String getPlataeformType() {
        return plataeformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column str_store.PLATAEFORM_TYPE
     *
     * @param plataeformType the value for str_store.PLATAEFORM_TYPE
     *
     * @mbg.generated
     */
    public void setPlataeformType(String plataeformType) {
        this.plataeformType = plataeformType == null ? null : plataeformType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column str_store.STORE_NAME
     *
     * @return the value of str_store.STORE_NAME
     *
     * @mbg.generated
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column str_store.STORE_NAME
     *
     * @param storeName the value for str_store.STORE_NAME
     *
     * @mbg.generated
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column str_store.STORE_STS_CD
     *
     * @return the value of str_store.STORE_STS_CD
     *
     * @mbg.generated
     */
    public String getStoreStsCd() {
        return storeStsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column str_store.STORE_STS_CD
     *
     * @param storeStsCd the value for str_store.STORE_STS_CD
     *
     * @mbg.generated
     */
    public void setStoreStsCd(String storeStsCd) {
        this.storeStsCd = storeStsCd == null ? null : storeStsCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column str_store.CREATED_BY
     *
     * @return the value of str_store.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column str_store.CREATED_BY
     *
     * @param createdBy the value for str_store.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column str_store.CREATION_DATE
     *
     * @return the value of str_store.CREATION_DATE
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column str_store.CREATION_DATE
     *
     * @param creationDate the value for str_store.CREATION_DATE
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column str_store.LAST_UPDATE_BY
     *
     * @return the value of str_store.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column str_store.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for str_store.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column str_store.LAST_UPDATE_DATE
     *
     * @return the value of str_store.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column str_store.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for str_store.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column str_store.CALL_CNT
     *
     * @return the value of str_store.CALL_CNT
     *
     * @mbg.generated
     */
    public Integer getCallCnt() {
        return callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column str_store.CALL_CNT
     *
     * @param callCnt the value for str_store.CALL_CNT
     *
     * @mbg.generated
     */
    public void setCallCnt(Integer callCnt) {
        this.callCnt = callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column str_store.STS_CD
     *
     * @return the value of str_store.STS_CD
     *
     * @mbg.generated
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column str_store.STS_CD
     *
     * @param stsCd the value for str_store.STS_CD
     *
     * @mbg.generated
     */
    public void setStsCd(String stsCd) {
        this.stsCd = stsCd == null ? null : stsCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column str_store.REMARK
     *
     * @return the value of str_store.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column str_store.REMARK
     *
     * @param remark the value for str_store.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}