package com.neusoft.bsp.model;

import java.math.BigDecimal;
import java.util.Date;

public class storeOrderLineItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sol_store_order_line_item.SOL_ID
     *
     * @mbg.generated
     */
    private Integer solId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sol_store_order_line_item.ORDER_ITEM_ID
     *
     * @mbg.generated
     */
    private String orderItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sol_store_order_line_item.STO_ID
     *
     * @mbg.generated
     */
    private Integer stoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sol_store_order_line_item.SALES_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal salesPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sol_store_order_line_item.QTY
     *
     * @mbg.generated
     */
    private Integer qty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sol_store_order_line_item.SKU_NO
     *
     * @mbg.generated
     */
    private String skuNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sol_store_order_line_item.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sol_store_order_line_item.CREATION_DATE
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sol_store_order_line_item.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sol_store_order_line_item.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sol_store_order_line_item.CALL_CNT
     *
     * @mbg.generated
     */
    private Integer callCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sol_store_order_line_item.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sol_store_order_line_item.STS_CD
     *
     * @mbg.generated
     */
    private String stsCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sol_store_order_line_item.BUYER_CHECKOUT_MESSAGE
     *
     * @mbg.generated
     */
    private String buyerCheckoutMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sol_store_order_line_item
     *
     * @mbg.generated
     */
    public storeOrderLineItem(Integer solId, String orderItemId, Integer stoId, BigDecimal salesPrice, Integer qty, String skuNo, String createdBy, Date creationDate, String lastUpdateBy, Date lastUpdateDate, Integer callCnt, String remark, String stsCd, String buyerCheckoutMessage) {
        this.solId = solId;
        this.orderItemId = orderItemId;
        this.stoId = stoId;
        this.salesPrice = salesPrice;
        this.qty = qty;
        this.skuNo = skuNo;
        this.createdBy = createdBy;
        this.creationDate = creationDate;
        this.lastUpdateBy = lastUpdateBy;
        this.lastUpdateDate = lastUpdateDate;
        this.callCnt = callCnt;
        this.remark = remark;
        this.stsCd = stsCd;
        this.buyerCheckoutMessage = buyerCheckoutMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sol_store_order_line_item
     *
     * @mbg.generated
     */
    public storeOrderLineItem() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sol_store_order_line_item.SOL_ID
     *
     * @return the value of sol_store_order_line_item.SOL_ID
     *
     * @mbg.generated
     */
    public Integer getSolId() {
        return solId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sol_store_order_line_item.SOL_ID
     *
     * @param solId the value for sol_store_order_line_item.SOL_ID
     *
     * @mbg.generated
     */
    public void setSolId(Integer solId) {
        this.solId = solId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sol_store_order_line_item.ORDER_ITEM_ID
     *
     * @return the value of sol_store_order_line_item.ORDER_ITEM_ID
     *
     * @mbg.generated
     */
    public String getOrderItemId() {
        return orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sol_store_order_line_item.ORDER_ITEM_ID
     *
     * @param orderItemId the value for sol_store_order_line_item.ORDER_ITEM_ID
     *
     * @mbg.generated
     */
    public void setOrderItemId(String orderItemId) {
        this.orderItemId = orderItemId == null ? null : orderItemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sol_store_order_line_item.STO_ID
     *
     * @return the value of sol_store_order_line_item.STO_ID
     *
     * @mbg.generated
     */
    public Integer getStoId() {
        return stoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sol_store_order_line_item.STO_ID
     *
     * @param stoId the value for sol_store_order_line_item.STO_ID
     *
     * @mbg.generated
     */
    public void setStoId(Integer stoId) {
        this.stoId = stoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sol_store_order_line_item.SALES_PRICE
     *
     * @return the value of sol_store_order_line_item.SALES_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getSalesPrice() {
        return salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sol_store_order_line_item.SALES_PRICE
     *
     * @param salesPrice the value for sol_store_order_line_item.SALES_PRICE
     *
     * @mbg.generated
     */
    public void setSalesPrice(BigDecimal salesPrice) {
        this.salesPrice = salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sol_store_order_line_item.QTY
     *
     * @return the value of sol_store_order_line_item.QTY
     *
     * @mbg.generated
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sol_store_order_line_item.QTY
     *
     * @param qty the value for sol_store_order_line_item.QTY
     *
     * @mbg.generated
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sol_store_order_line_item.SKU_NO
     *
     * @return the value of sol_store_order_line_item.SKU_NO
     *
     * @mbg.generated
     */
    public String getSkuNo() {
        return skuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sol_store_order_line_item.SKU_NO
     *
     * @param skuNo the value for sol_store_order_line_item.SKU_NO
     *
     * @mbg.generated
     */
    public void setSkuNo(String skuNo) {
        this.skuNo = skuNo == null ? null : skuNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sol_store_order_line_item.CREATED_BY
     *
     * @return the value of sol_store_order_line_item.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sol_store_order_line_item.CREATED_BY
     *
     * @param createdBy the value for sol_store_order_line_item.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sol_store_order_line_item.CREATION_DATE
     *
     * @return the value of sol_store_order_line_item.CREATION_DATE
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sol_store_order_line_item.CREATION_DATE
     *
     * @param creationDate the value for sol_store_order_line_item.CREATION_DATE
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sol_store_order_line_item.LAST_UPDATE_BY
     *
     * @return the value of sol_store_order_line_item.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sol_store_order_line_item.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for sol_store_order_line_item.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sol_store_order_line_item.LAST_UPDATE_DATE
     *
     * @return the value of sol_store_order_line_item.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sol_store_order_line_item.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for sol_store_order_line_item.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sol_store_order_line_item.CALL_CNT
     *
     * @return the value of sol_store_order_line_item.CALL_CNT
     *
     * @mbg.generated
     */
    public Integer getCallCnt() {
        return callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sol_store_order_line_item.CALL_CNT
     *
     * @param callCnt the value for sol_store_order_line_item.CALL_CNT
     *
     * @mbg.generated
     */
    public void setCallCnt(Integer callCnt) {
        this.callCnt = callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sol_store_order_line_item.REMARK
     *
     * @return the value of sol_store_order_line_item.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sol_store_order_line_item.REMARK
     *
     * @param remark the value for sol_store_order_line_item.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sol_store_order_line_item.STS_CD
     *
     * @return the value of sol_store_order_line_item.STS_CD
     *
     * @mbg.generated
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sol_store_order_line_item.STS_CD
     *
     * @param stsCd the value for sol_store_order_line_item.STS_CD
     *
     * @mbg.generated
     */
    public void setStsCd(String stsCd) {
        this.stsCd = stsCd == null ? null : stsCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sol_store_order_line_item.BUYER_CHECKOUT_MESSAGE
     *
     * @return the value of sol_store_order_line_item.BUYER_CHECKOUT_MESSAGE
     *
     * @mbg.generated
     */
    public String getBuyerCheckoutMessage() {
        return buyerCheckoutMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sol_store_order_line_item.BUYER_CHECKOUT_MESSAGE
     *
     * @param buyerCheckoutMessage the value for sol_store_order_line_item.BUYER_CHECKOUT_MESSAGE
     *
     * @mbg.generated
     */
    public void setBuyerCheckoutMessage(String buyerCheckoutMessage) {
        this.buyerCheckoutMessage = buyerCheckoutMessage == null ? null : buyerCheckoutMessage.trim();
    }
}