package com.neusoft.bsp.model;

import java.math.BigDecimal;
import java.util.Date;

public class storeDropshipItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdi_store_dropship_item.DIL_ID
     *
     * @mbg.generated
     */
    private Integer dilId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdi_store_dropship_item.PRO_ID
     *
     * @mbg.generated
     */
    private Integer proId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdi_store_dropship_item.STR_ID
     *
     * @mbg.generated
     */
    private Integer strId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdi_store_dropship_item.STORE_RETENTION
     *
     * @mbg.generated
     */
    private Integer storeRetention;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdi_store_dropship_item.DROPSHIP_PRICE
     *
     * @mbg.generated
     */
    private BigDecimal dropshipPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdi_store_dropship_item.DROPSHIP_STATUS
     *
     * @mbg.generated
     */
    private String dropshipStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdi_store_dropship_item.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdi_store_dropship_item.CREATION_DATE
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdi_store_dropship_item.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdi_store_dropship_item.CALL_CNT
     *
     * @mbg.generated
     */
    private Integer callCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdi_store_dropship_item.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdi_store_dropship_item.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdi_store_dropship_item.STS_CD
     *
     * @mbg.generated
     */
    private String stsCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdi_store_dropship_item.SHELF_STOCK
     *
     * @mbg.generated
     */
    private Integer shelfStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdi_store_dropship_item.PREFER_DATE
     *
     * @mbg.generated
     */
    private Date preferDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdi_store_dropship_item
     *
     * @mbg.generated
     */
    public storeDropshipItem(Integer dilId, Integer proId, Integer strId, Integer storeRetention, BigDecimal dropshipPrice, String dropshipStatus, String createdBy, Date creationDate, String lastUpdateBy, Integer callCnt, Date lastUpdateDate, String remark, String stsCd, Integer shelfStock, Date preferDate) {
        this.dilId = dilId;
        this.proId = proId;
        this.strId = strId;
        this.storeRetention = storeRetention;
        this.dropshipPrice = dropshipPrice;
        this.dropshipStatus = dropshipStatus;
        this.createdBy = createdBy;
        this.creationDate = creationDate;
        this.lastUpdateBy = lastUpdateBy;
        this.callCnt = callCnt;
        this.lastUpdateDate = lastUpdateDate;
        this.remark = remark;
        this.stsCd = stsCd;
        this.shelfStock = shelfStock;
        this.preferDate = preferDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdi_store_dropship_item
     *
     * @mbg.generated
     */
    public storeDropshipItem() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdi_store_dropship_item.DIL_ID
     *
     * @return the value of sdi_store_dropship_item.DIL_ID
     *
     * @mbg.generated
     */
    public Integer getDilId() {
        return dilId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdi_store_dropship_item.DIL_ID
     *
     * @param dilId the value for sdi_store_dropship_item.DIL_ID
     *
     * @mbg.generated
     */
    public void setDilId(Integer dilId) {
        this.dilId = dilId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdi_store_dropship_item.PRO_ID
     *
     * @return the value of sdi_store_dropship_item.PRO_ID
     *
     * @mbg.generated
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdi_store_dropship_item.PRO_ID
     *
     * @param proId the value for sdi_store_dropship_item.PRO_ID
     *
     * @mbg.generated
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdi_store_dropship_item.STR_ID
     *
     * @return the value of sdi_store_dropship_item.STR_ID
     *
     * @mbg.generated
     */
    public Integer getStrId() {
        return strId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdi_store_dropship_item.STR_ID
     *
     * @param strId the value for sdi_store_dropship_item.STR_ID
     *
     * @mbg.generated
     */
    public void setStrId(Integer strId) {
        this.strId = strId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdi_store_dropship_item.STORE_RETENTION
     *
     * @return the value of sdi_store_dropship_item.STORE_RETENTION
     *
     * @mbg.generated
     */
    public Integer getStoreRetention() {
        return storeRetention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdi_store_dropship_item.STORE_RETENTION
     *
     * @param storeRetention the value for sdi_store_dropship_item.STORE_RETENTION
     *
     * @mbg.generated
     */
    public void setStoreRetention(Integer storeRetention) {
        this.storeRetention = storeRetention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdi_store_dropship_item.DROPSHIP_PRICE
     *
     * @return the value of sdi_store_dropship_item.DROPSHIP_PRICE
     *
     * @mbg.generated
     */
    public BigDecimal getDropshipPrice() {
        return dropshipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdi_store_dropship_item.DROPSHIP_PRICE
     *
     * @param dropshipPrice the value for sdi_store_dropship_item.DROPSHIP_PRICE
     *
     * @mbg.generated
     */
    public void setDropshipPrice(BigDecimal dropshipPrice) {
        this.dropshipPrice = dropshipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdi_store_dropship_item.DROPSHIP_STATUS
     *
     * @return the value of sdi_store_dropship_item.DROPSHIP_STATUS
     *
     * @mbg.generated
     */
    public String getDropshipStatus() {
        return dropshipStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdi_store_dropship_item.DROPSHIP_STATUS
     *
     * @param dropshipStatus the value for sdi_store_dropship_item.DROPSHIP_STATUS
     *
     * @mbg.generated
     */
    public void setDropshipStatus(String dropshipStatus) {
        this.dropshipStatus = dropshipStatus == null ? null : dropshipStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdi_store_dropship_item.CREATED_BY
     *
     * @return the value of sdi_store_dropship_item.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdi_store_dropship_item.CREATED_BY
     *
     * @param createdBy the value for sdi_store_dropship_item.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdi_store_dropship_item.CREATION_DATE
     *
     * @return the value of sdi_store_dropship_item.CREATION_DATE
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdi_store_dropship_item.CREATION_DATE
     *
     * @param creationDate the value for sdi_store_dropship_item.CREATION_DATE
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdi_store_dropship_item.LAST_UPDATE_BY
     *
     * @return the value of sdi_store_dropship_item.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdi_store_dropship_item.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for sdi_store_dropship_item.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdi_store_dropship_item.CALL_CNT
     *
     * @return the value of sdi_store_dropship_item.CALL_CNT
     *
     * @mbg.generated
     */
    public Integer getCallCnt() {
        return callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdi_store_dropship_item.CALL_CNT
     *
     * @param callCnt the value for sdi_store_dropship_item.CALL_CNT
     *
     * @mbg.generated
     */
    public void setCallCnt(Integer callCnt) {
        this.callCnt = callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdi_store_dropship_item.LAST_UPDATE_DATE
     *
     * @return the value of sdi_store_dropship_item.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdi_store_dropship_item.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for sdi_store_dropship_item.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdi_store_dropship_item.REMARK
     *
     * @return the value of sdi_store_dropship_item.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdi_store_dropship_item.REMARK
     *
     * @param remark the value for sdi_store_dropship_item.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdi_store_dropship_item.STS_CD
     *
     * @return the value of sdi_store_dropship_item.STS_CD
     *
     * @mbg.generated
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdi_store_dropship_item.STS_CD
     *
     * @param stsCd the value for sdi_store_dropship_item.STS_CD
     *
     * @mbg.generated
     */
    public void setStsCd(String stsCd) {
        this.stsCd = stsCd == null ? null : stsCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdi_store_dropship_item.SHELF_STOCK
     *
     * @return the value of sdi_store_dropship_item.SHELF_STOCK
     *
     * @mbg.generated
     */
    public Integer getShelfStock() {
        return shelfStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdi_store_dropship_item.SHELF_STOCK
     *
     * @param shelfStock the value for sdi_store_dropship_item.SHELF_STOCK
     *
     * @mbg.generated
     */
    public void setShelfStock(Integer shelfStock) {
        this.shelfStock = shelfStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdi_store_dropship_item.PREFER_DATE
     *
     * @return the value of sdi_store_dropship_item.PREFER_DATE
     *
     * @mbg.generated
     */
    public Date getPreferDate() {
        return preferDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdi_store_dropship_item.PREFER_DATE
     *
     * @param preferDate the value for sdi_store_dropship_item.PREFER_DATE
     *
     * @mbg.generated
     */
    public void setPreferDate(Date preferDate) {
        this.preferDate = preferDate;
    }
}