package com.neusoft.bsp.model;

import java.util.Date;

public class userloginLogoutLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ull_user_login_logout_log.ULL_ID
     *
     * @mbg.generated
     */
    private Integer ullId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ull_user_login_logout_log.USER_ID
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ull_user_login_logout_log.TOKEN
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ull_user_login_logout_log.TERMINAL_TYPE
     *
     * @mbg.generated
     */
    private String terminalType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ull_user_login_logout_log.OPERATING_TYPE
     *
     * @mbg.generated
     */
    private String operatingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ull_user_login_logout_log.OPERATING_DATE
     *
     * @mbg.generated
     */
    private Date operatingDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ull_user_login_logout_log.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ull_user_login_logout_log.CREATION_DATE
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ull_user_login_logout_log.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ull_user_login_logout_log.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ull_user_login_logout_log.CALL_CNT
     *
     * @mbg.generated
     */
    private Integer callCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ull_user_login_logout_log.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ull_user_login_logout_log.STS_CD
     *
     * @mbg.generated
     */
    private String stsCd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ull_user_login_logout_log
     *
     * @mbg.generated
     */
    public userloginLogoutLog(Integer ullId, String userId, String token, String terminalType, String operatingType, Date operatingDate, String createdBy, Date creationDate, String lastUpdateBy, Date lastUpdateDate, Integer callCnt, String remark, String stsCd) {
        this.ullId = ullId;
        this.userId = userId;
        this.token = token;
        this.terminalType = terminalType;
        this.operatingType = operatingType;
        this.operatingDate = operatingDate;
        this.createdBy = createdBy;
        this.creationDate = creationDate;
        this.lastUpdateBy = lastUpdateBy;
        this.lastUpdateDate = lastUpdateDate;
        this.callCnt = callCnt;
        this.remark = remark;
        this.stsCd = stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ull_user_login_logout_log
     *
     * @mbg.generated
     */
    public userloginLogoutLog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ull_user_login_logout_log.ULL_ID
     *
     * @return the value of ull_user_login_logout_log.ULL_ID
     *
     * @mbg.generated
     */
    public Integer getUllId() {
        return ullId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ull_user_login_logout_log.ULL_ID
     *
     * @param ullId the value for ull_user_login_logout_log.ULL_ID
     *
     * @mbg.generated
     */
    public void setUllId(Integer ullId) {
        this.ullId = ullId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ull_user_login_logout_log.USER_ID
     *
     * @return the value of ull_user_login_logout_log.USER_ID
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ull_user_login_logout_log.USER_ID
     *
     * @param userId the value for ull_user_login_logout_log.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ull_user_login_logout_log.TOKEN
     *
     * @return the value of ull_user_login_logout_log.TOKEN
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ull_user_login_logout_log.TOKEN
     *
     * @param token the value for ull_user_login_logout_log.TOKEN
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ull_user_login_logout_log.TERMINAL_TYPE
     *
     * @return the value of ull_user_login_logout_log.TERMINAL_TYPE
     *
     * @mbg.generated
     */
    public String getTerminalType() {
        return terminalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ull_user_login_logout_log.TERMINAL_TYPE
     *
     * @param terminalType the value for ull_user_login_logout_log.TERMINAL_TYPE
     *
     * @mbg.generated
     */
    public void setTerminalType(String terminalType) {
        this.terminalType = terminalType == null ? null : terminalType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ull_user_login_logout_log.OPERATING_TYPE
     *
     * @return the value of ull_user_login_logout_log.OPERATING_TYPE
     *
     * @mbg.generated
     */
    public String getOperatingType() {
        return operatingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ull_user_login_logout_log.OPERATING_TYPE
     *
     * @param operatingType the value for ull_user_login_logout_log.OPERATING_TYPE
     *
     * @mbg.generated
     */
    public void setOperatingType(String operatingType) {
        this.operatingType = operatingType == null ? null : operatingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ull_user_login_logout_log.OPERATING_DATE
     *
     * @return the value of ull_user_login_logout_log.OPERATING_DATE
     *
     * @mbg.generated
     */
    public Date getOperatingDate() {
        return operatingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ull_user_login_logout_log.OPERATING_DATE
     *
     * @param operatingDate the value for ull_user_login_logout_log.OPERATING_DATE
     *
     * @mbg.generated
     */
    public void setOperatingDate(Date operatingDate) {
        this.operatingDate = operatingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ull_user_login_logout_log.CREATED_BY
     *
     * @return the value of ull_user_login_logout_log.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ull_user_login_logout_log.CREATED_BY
     *
     * @param createdBy the value for ull_user_login_logout_log.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ull_user_login_logout_log.CREATION_DATE
     *
     * @return the value of ull_user_login_logout_log.CREATION_DATE
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ull_user_login_logout_log.CREATION_DATE
     *
     * @param creationDate the value for ull_user_login_logout_log.CREATION_DATE
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ull_user_login_logout_log.LAST_UPDATE_BY
     *
     * @return the value of ull_user_login_logout_log.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ull_user_login_logout_log.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for ull_user_login_logout_log.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ull_user_login_logout_log.LAST_UPDATE_DATE
     *
     * @return the value of ull_user_login_logout_log.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ull_user_login_logout_log.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for ull_user_login_logout_log.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ull_user_login_logout_log.CALL_CNT
     *
     * @return the value of ull_user_login_logout_log.CALL_CNT
     *
     * @mbg.generated
     */
    public Integer getCallCnt() {
        return callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ull_user_login_logout_log.CALL_CNT
     *
     * @param callCnt the value for ull_user_login_logout_log.CALL_CNT
     *
     * @mbg.generated
     */
    public void setCallCnt(Integer callCnt) {
        this.callCnt = callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ull_user_login_logout_log.REMARK
     *
     * @return the value of ull_user_login_logout_log.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ull_user_login_logout_log.REMARK
     *
     * @param remark the value for ull_user_login_logout_log.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ull_user_login_logout_log.STS_CD
     *
     * @return the value of ull_user_login_logout_log.STS_CD
     *
     * @mbg.generated
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ull_user_login_logout_log.STS_CD
     *
     * @param stsCd the value for ull_user_login_logout_log.STS_CD
     *
     * @mbg.generated
     */
    public void setStsCd(String stsCd) {
        this.stsCd = stsCd == null ? null : stsCd.trim();
    }
}