package com.neusoft.bsp.model;

import java.math.BigDecimal;
import java.util.Date;

public class walletTransactionRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.TRANSACTION_ID
     *
     * @mbg.generated
     */
    private Integer transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.BUYER_ID
     *
     * @mbg.generated
     */
    private Integer buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.BANK_CARD_ID
     *
     * @mbg.generated
     */
    private Integer bankCardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.TRANSACTION_NUMBER
     *
     * @mbg.generated
     */
    private String transactionNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.TRANSACTION_TYPE
     *
     * @mbg.generated
     */
    private Byte transactionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.ACCOUNT_NAME
     *
     * @mbg.generated
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.TRANSACTION_MONEY
     *
     * @mbg.generated
     */
    private BigDecimal transactionMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.COMMISSION
     *
     * @mbg.generated
     */
    private BigDecimal commission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.DISCOUNT_COMMISSION
     *
     * @mbg.generated
     */
    private BigDecimal discountCommission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.TRANSACTION_METHOD
     *
     * @mbg.generated
     */
    private Byte transactionMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.COMPLETE_TIME
     *
     * @mbg.generated
     */
    private Date completeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.STATUS
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.ACTUAL_MONEY
     *
     * @mbg.generated
     */
    private BigDecimal actualMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.ACTUAL_COMMISSION
     *
     * @mbg.generated
     */
    private BigDecimal actualCommission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.ACTUAL_DISCOUNT_COMMISSION
     *
     * @mbg.generated
     */
    private BigDecimal actualDiscountCommission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.BALANCE
     *
     * @mbg.generated
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.BUSINESS_ID
     *
     * @mbg.generated
     */
    private Integer businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.FINANCE_TYPE
     *
     * @mbg.generated
     */
    private Byte financeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.NOTE
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.OPERATOR_NAME
     *
     * @mbg.generated
     */
    private String operatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.OPERATOR_IP
     *
     * @mbg.generated
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.BANK_RECEIPT_URL
     *
     * @mbg.generated
     */
    private String bankReceiptUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.EXCHANGE_RATE
     *
     * @mbg.generated
     */
    private BigDecimal exchangeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.TRANSACTION_DESC
     *
     * @mbg.generated
     */
    private String transactionDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.FOREIGN_EXCHANGE_FEE
     *
     * @mbg.generated
     */
    private BigDecimal foreignExchangeFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wtr_wallet_transaction_record.WITHDRAW_FEE
     *
     * @mbg.generated
     */
    private BigDecimal withdrawFee;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wtr_wallet_transaction_record
     *
     * @mbg.generated
     */
    public walletTransactionRecord(Integer transactionId, Integer buyerId, Integer bankCardId, String transactionNumber, Byte transactionType, String accountName, BigDecimal transactionMoney, BigDecimal commission, BigDecimal discountCommission, Byte transactionMethod, Date completeTime, Byte status, BigDecimal actualMoney, BigDecimal actualCommission, BigDecimal actualDiscountCommission, BigDecimal balance, Integer businessId, Byte financeType, String note, String operatorName, String operatorIp, String createBy, Date createTime, String lastUpdateBy, Date lastUpdateTime, String bankReceiptUrl, BigDecimal exchangeRate, String transactionDesc, BigDecimal foreignExchangeFee, BigDecimal withdrawFee) {
        this.transactionId = transactionId;
        this.buyerId = buyerId;
        this.bankCardId = bankCardId;
        this.transactionNumber = transactionNumber;
        this.transactionType = transactionType;
        this.accountName = accountName;
        this.transactionMoney = transactionMoney;
        this.commission = commission;
        this.discountCommission = discountCommission;
        this.transactionMethod = transactionMethod;
        this.completeTime = completeTime;
        this.status = status;
        this.actualMoney = actualMoney;
        this.actualCommission = actualCommission;
        this.actualDiscountCommission = actualDiscountCommission;
        this.balance = balance;
        this.businessId = businessId;
        this.financeType = financeType;
        this.note = note;
        this.operatorName = operatorName;
        this.operatorIp = operatorIp;
        this.createBy = createBy;
        this.createTime = createTime;
        this.lastUpdateBy = lastUpdateBy;
        this.lastUpdateTime = lastUpdateTime;
        this.bankReceiptUrl = bankReceiptUrl;
        this.exchangeRate = exchangeRate;
        this.transactionDesc = transactionDesc;
        this.foreignExchangeFee = foreignExchangeFee;
        this.withdrawFee = withdrawFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wtr_wallet_transaction_record
     *
     * @mbg.generated
     */
    public walletTransactionRecord() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.TRANSACTION_ID
     *
     * @return the value of wtr_wallet_transaction_record.TRANSACTION_ID
     *
     * @mbg.generated
     */
    public Integer getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.TRANSACTION_ID
     *
     * @param transactionId the value for wtr_wallet_transaction_record.TRANSACTION_ID
     *
     * @mbg.generated
     */
    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.BUYER_ID
     *
     * @return the value of wtr_wallet_transaction_record.BUYER_ID
     *
     * @mbg.generated
     */
    public Integer getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.BUYER_ID
     *
     * @param buyerId the value for wtr_wallet_transaction_record.BUYER_ID
     *
     * @mbg.generated
     */
    public void setBuyerId(Integer buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.BANK_CARD_ID
     *
     * @return the value of wtr_wallet_transaction_record.BANK_CARD_ID
     *
     * @mbg.generated
     */
    public Integer getBankCardId() {
        return bankCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.BANK_CARD_ID
     *
     * @param bankCardId the value for wtr_wallet_transaction_record.BANK_CARD_ID
     *
     * @mbg.generated
     */
    public void setBankCardId(Integer bankCardId) {
        this.bankCardId = bankCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.TRANSACTION_NUMBER
     *
     * @return the value of wtr_wallet_transaction_record.TRANSACTION_NUMBER
     *
     * @mbg.generated
     */
    public String getTransactionNumber() {
        return transactionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.TRANSACTION_NUMBER
     *
     * @param transactionNumber the value for wtr_wallet_transaction_record.TRANSACTION_NUMBER
     *
     * @mbg.generated
     */
    public void setTransactionNumber(String transactionNumber) {
        this.transactionNumber = transactionNumber == null ? null : transactionNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.TRANSACTION_TYPE
     *
     * @return the value of wtr_wallet_transaction_record.TRANSACTION_TYPE
     *
     * @mbg.generated
     */
    public Byte getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.TRANSACTION_TYPE
     *
     * @param transactionType the value for wtr_wallet_transaction_record.TRANSACTION_TYPE
     *
     * @mbg.generated
     */
    public void setTransactionType(Byte transactionType) {
        this.transactionType = transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.ACCOUNT_NAME
     *
     * @return the value of wtr_wallet_transaction_record.ACCOUNT_NAME
     *
     * @mbg.generated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.ACCOUNT_NAME
     *
     * @param accountName the value for wtr_wallet_transaction_record.ACCOUNT_NAME
     *
     * @mbg.generated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.TRANSACTION_MONEY
     *
     * @return the value of wtr_wallet_transaction_record.TRANSACTION_MONEY
     *
     * @mbg.generated
     */
    public BigDecimal getTransactionMoney() {
        return transactionMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.TRANSACTION_MONEY
     *
     * @param transactionMoney the value for wtr_wallet_transaction_record.TRANSACTION_MONEY
     *
     * @mbg.generated
     */
    public void setTransactionMoney(BigDecimal transactionMoney) {
        this.transactionMoney = transactionMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.COMMISSION
     *
     * @return the value of wtr_wallet_transaction_record.COMMISSION
     *
     * @mbg.generated
     */
    public BigDecimal getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.COMMISSION
     *
     * @param commission the value for wtr_wallet_transaction_record.COMMISSION
     *
     * @mbg.generated
     */
    public void setCommission(BigDecimal commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.DISCOUNT_COMMISSION
     *
     * @return the value of wtr_wallet_transaction_record.DISCOUNT_COMMISSION
     *
     * @mbg.generated
     */
    public BigDecimal getDiscountCommission() {
        return discountCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.DISCOUNT_COMMISSION
     *
     * @param discountCommission the value for wtr_wallet_transaction_record.DISCOUNT_COMMISSION
     *
     * @mbg.generated
     */
    public void setDiscountCommission(BigDecimal discountCommission) {
        this.discountCommission = discountCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.TRANSACTION_METHOD
     *
     * @return the value of wtr_wallet_transaction_record.TRANSACTION_METHOD
     *
     * @mbg.generated
     */
    public Byte getTransactionMethod() {
        return transactionMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.TRANSACTION_METHOD
     *
     * @param transactionMethod the value for wtr_wallet_transaction_record.TRANSACTION_METHOD
     *
     * @mbg.generated
     */
    public void setTransactionMethod(Byte transactionMethod) {
        this.transactionMethod = transactionMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.COMPLETE_TIME
     *
     * @return the value of wtr_wallet_transaction_record.COMPLETE_TIME
     *
     * @mbg.generated
     */
    public Date getCompleteTime() {
        return completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.COMPLETE_TIME
     *
     * @param completeTime the value for wtr_wallet_transaction_record.COMPLETE_TIME
     *
     * @mbg.generated
     */
    public void setCompleteTime(Date completeTime) {
        this.completeTime = completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.STATUS
     *
     * @return the value of wtr_wallet_transaction_record.STATUS
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.STATUS
     *
     * @param status the value for wtr_wallet_transaction_record.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.ACTUAL_MONEY
     *
     * @return the value of wtr_wallet_transaction_record.ACTUAL_MONEY
     *
     * @mbg.generated
     */
    public BigDecimal getActualMoney() {
        return actualMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.ACTUAL_MONEY
     *
     * @param actualMoney the value for wtr_wallet_transaction_record.ACTUAL_MONEY
     *
     * @mbg.generated
     */
    public void setActualMoney(BigDecimal actualMoney) {
        this.actualMoney = actualMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.ACTUAL_COMMISSION
     *
     * @return the value of wtr_wallet_transaction_record.ACTUAL_COMMISSION
     *
     * @mbg.generated
     */
    public BigDecimal getActualCommission() {
        return actualCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.ACTUAL_COMMISSION
     *
     * @param actualCommission the value for wtr_wallet_transaction_record.ACTUAL_COMMISSION
     *
     * @mbg.generated
     */
    public void setActualCommission(BigDecimal actualCommission) {
        this.actualCommission = actualCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.ACTUAL_DISCOUNT_COMMISSION
     *
     * @return the value of wtr_wallet_transaction_record.ACTUAL_DISCOUNT_COMMISSION
     *
     * @mbg.generated
     */
    public BigDecimal getActualDiscountCommission() {
        return actualDiscountCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.ACTUAL_DISCOUNT_COMMISSION
     *
     * @param actualDiscountCommission the value for wtr_wallet_transaction_record.ACTUAL_DISCOUNT_COMMISSION
     *
     * @mbg.generated
     */
    public void setActualDiscountCommission(BigDecimal actualDiscountCommission) {
        this.actualDiscountCommission = actualDiscountCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.BALANCE
     *
     * @return the value of wtr_wallet_transaction_record.BALANCE
     *
     * @mbg.generated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.BALANCE
     *
     * @param balance the value for wtr_wallet_transaction_record.BALANCE
     *
     * @mbg.generated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.BUSINESS_ID
     *
     * @return the value of wtr_wallet_transaction_record.BUSINESS_ID
     *
     * @mbg.generated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.BUSINESS_ID
     *
     * @param businessId the value for wtr_wallet_transaction_record.BUSINESS_ID
     *
     * @mbg.generated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.FINANCE_TYPE
     *
     * @return the value of wtr_wallet_transaction_record.FINANCE_TYPE
     *
     * @mbg.generated
     */
    public Byte getFinanceType() {
        return financeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.FINANCE_TYPE
     *
     * @param financeType the value for wtr_wallet_transaction_record.FINANCE_TYPE
     *
     * @mbg.generated
     */
    public void setFinanceType(Byte financeType) {
        this.financeType = financeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.NOTE
     *
     * @return the value of wtr_wallet_transaction_record.NOTE
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.NOTE
     *
     * @param note the value for wtr_wallet_transaction_record.NOTE
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.OPERATOR_NAME
     *
     * @return the value of wtr_wallet_transaction_record.OPERATOR_NAME
     *
     * @mbg.generated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.OPERATOR_NAME
     *
     * @param operatorName the value for wtr_wallet_transaction_record.OPERATOR_NAME
     *
     * @mbg.generated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.OPERATOR_IP
     *
     * @return the value of wtr_wallet_transaction_record.OPERATOR_IP
     *
     * @mbg.generated
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.OPERATOR_IP
     *
     * @param operatorIp the value for wtr_wallet_transaction_record.OPERATOR_IP
     *
     * @mbg.generated
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.CREATE_BY
     *
     * @return the value of wtr_wallet_transaction_record.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.CREATE_BY
     *
     * @param createBy the value for wtr_wallet_transaction_record.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.CREATE_TIME
     *
     * @return the value of wtr_wallet_transaction_record.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.CREATE_TIME
     *
     * @param createTime the value for wtr_wallet_transaction_record.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.LAST_UPDATE_BY
     *
     * @return the value of wtr_wallet_transaction_record.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for wtr_wallet_transaction_record.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.LAST_UPDATE_TIME
     *
     * @return the value of wtr_wallet_transaction_record.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for wtr_wallet_transaction_record.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.BANK_RECEIPT_URL
     *
     * @return the value of wtr_wallet_transaction_record.BANK_RECEIPT_URL
     *
     * @mbg.generated
     */
    public String getBankReceiptUrl() {
        return bankReceiptUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.BANK_RECEIPT_URL
     *
     * @param bankReceiptUrl the value for wtr_wallet_transaction_record.BANK_RECEIPT_URL
     *
     * @mbg.generated
     */
    public void setBankReceiptUrl(String bankReceiptUrl) {
        this.bankReceiptUrl = bankReceiptUrl == null ? null : bankReceiptUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.EXCHANGE_RATE
     *
     * @return the value of wtr_wallet_transaction_record.EXCHANGE_RATE
     *
     * @mbg.generated
     */
    public BigDecimal getExchangeRate() {
        return exchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.EXCHANGE_RATE
     *
     * @param exchangeRate the value for wtr_wallet_transaction_record.EXCHANGE_RATE
     *
     * @mbg.generated
     */
    public void setExchangeRate(BigDecimal exchangeRate) {
        this.exchangeRate = exchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.TRANSACTION_DESC
     *
     * @return the value of wtr_wallet_transaction_record.TRANSACTION_DESC
     *
     * @mbg.generated
     */
    public String getTransactionDesc() {
        return transactionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.TRANSACTION_DESC
     *
     * @param transactionDesc the value for wtr_wallet_transaction_record.TRANSACTION_DESC
     *
     * @mbg.generated
     */
    public void setTransactionDesc(String transactionDesc) {
        this.transactionDesc = transactionDesc == null ? null : transactionDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.FOREIGN_EXCHANGE_FEE
     *
     * @return the value of wtr_wallet_transaction_record.FOREIGN_EXCHANGE_FEE
     *
     * @mbg.generated
     */
    public BigDecimal getForeignExchangeFee() {
        return foreignExchangeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.FOREIGN_EXCHANGE_FEE
     *
     * @param foreignExchangeFee the value for wtr_wallet_transaction_record.FOREIGN_EXCHANGE_FEE
     *
     * @mbg.generated
     */
    public void setForeignExchangeFee(BigDecimal foreignExchangeFee) {
        this.foreignExchangeFee = foreignExchangeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wtr_wallet_transaction_record.WITHDRAW_FEE
     *
     * @return the value of wtr_wallet_transaction_record.WITHDRAW_FEE
     *
     * @mbg.generated
     */
    public BigDecimal getWithdrawFee() {
        return withdrawFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wtr_wallet_transaction_record.WITHDRAW_FEE
     *
     * @param withdrawFee the value for wtr_wallet_transaction_record.WITHDRAW_FEE
     *
     * @mbg.generated
     */
    public void setWithdrawFee(BigDecimal withdrawFee) {
        this.withdrawFee = withdrawFee;
    }
}