package com.neusoft.bsp.model;

import java.util.Date;

public class walletAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waa_wallet_account.BUYER_ID
     *
     * @mbg.generated
     */
    private Integer buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waa_wallet_account.ACCOUNT_NAME
     *
     * @mbg.generated
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waa_wallet_account.EMAIL
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waa_wallet_account.PASSWORD
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waa_wallet_account.ACTIVE_TIME
     *
     * @mbg.generated
     */
    private Date activeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waa_wallet_account.IS_ACTIVE
     *
     * @mbg.generated
     */
    private String isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waa_wallet_account.STATUS
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waa_wallet_account.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waa_wallet_account.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waa_wallet_account.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waa_wallet_account.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waa_wallet_account.ACCOUNT_TYPE
     *
     * @mbg.generated
     */
    private Integer accountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waa_wallet_account.HOLD_ORDER_TIME
     *
     * @mbg.generated
     */
    private String holdOrderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waa_wallet_account.AUTO_PAY_STATUS
     *
     * @mbg.generated
     */
    private String autoPayStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waa_wallet_account
     *
     * @mbg.generated
     */
    public walletAccount(Integer buyerId, String accountName, String email, String password, Date activeTime, String isActive, Byte status, String createBy, Date createTime, String lastUpdateBy, Date lastUpdateTime, Integer accountType, String holdOrderTime, String autoPayStatus) {
        this.buyerId = buyerId;
        this.accountName = accountName;
        this.email = email;
        this.password = password;
        this.activeTime = activeTime;
        this.isActive = isActive;
        this.status = status;
        this.createBy = createBy;
        this.createTime = createTime;
        this.lastUpdateBy = lastUpdateBy;
        this.lastUpdateTime = lastUpdateTime;
        this.accountType = accountType;
        this.holdOrderTime = holdOrderTime;
        this.autoPayStatus = autoPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waa_wallet_account
     *
     * @mbg.generated
     */
    public walletAccount() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waa_wallet_account.BUYER_ID
     *
     * @return the value of waa_wallet_account.BUYER_ID
     *
     * @mbg.generated
     */
    public Integer getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waa_wallet_account.BUYER_ID
     *
     * @param buyerId the value for waa_wallet_account.BUYER_ID
     *
     * @mbg.generated
     */
    public void setBuyerId(Integer buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waa_wallet_account.ACCOUNT_NAME
     *
     * @return the value of waa_wallet_account.ACCOUNT_NAME
     *
     * @mbg.generated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waa_wallet_account.ACCOUNT_NAME
     *
     * @param accountName the value for waa_wallet_account.ACCOUNT_NAME
     *
     * @mbg.generated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waa_wallet_account.EMAIL
     *
     * @return the value of waa_wallet_account.EMAIL
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waa_wallet_account.EMAIL
     *
     * @param email the value for waa_wallet_account.EMAIL
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waa_wallet_account.PASSWORD
     *
     * @return the value of waa_wallet_account.PASSWORD
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waa_wallet_account.PASSWORD
     *
     * @param password the value for waa_wallet_account.PASSWORD
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waa_wallet_account.ACTIVE_TIME
     *
     * @return the value of waa_wallet_account.ACTIVE_TIME
     *
     * @mbg.generated
     */
    public Date getActiveTime() {
        return activeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waa_wallet_account.ACTIVE_TIME
     *
     * @param activeTime the value for waa_wallet_account.ACTIVE_TIME
     *
     * @mbg.generated
     */
    public void setActiveTime(Date activeTime) {
        this.activeTime = activeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waa_wallet_account.IS_ACTIVE
     *
     * @return the value of waa_wallet_account.IS_ACTIVE
     *
     * @mbg.generated
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waa_wallet_account.IS_ACTIVE
     *
     * @param isActive the value for waa_wallet_account.IS_ACTIVE
     *
     * @mbg.generated
     */
    public void setIsActive(String isActive) {
        this.isActive = isActive == null ? null : isActive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waa_wallet_account.STATUS
     *
     * @return the value of waa_wallet_account.STATUS
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waa_wallet_account.STATUS
     *
     * @param status the value for waa_wallet_account.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waa_wallet_account.CREATE_BY
     *
     * @return the value of waa_wallet_account.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waa_wallet_account.CREATE_BY
     *
     * @param createBy the value for waa_wallet_account.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waa_wallet_account.CREATE_TIME
     *
     * @return the value of waa_wallet_account.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waa_wallet_account.CREATE_TIME
     *
     * @param createTime the value for waa_wallet_account.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waa_wallet_account.LAST_UPDATE_BY
     *
     * @return the value of waa_wallet_account.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waa_wallet_account.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for waa_wallet_account.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waa_wallet_account.LAST_UPDATE_TIME
     *
     * @return the value of waa_wallet_account.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waa_wallet_account.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for waa_wallet_account.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waa_wallet_account.ACCOUNT_TYPE
     *
     * @return the value of waa_wallet_account.ACCOUNT_TYPE
     *
     * @mbg.generated
     */
    public Integer getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waa_wallet_account.ACCOUNT_TYPE
     *
     * @param accountType the value for waa_wallet_account.ACCOUNT_TYPE
     *
     * @mbg.generated
     */
    public void setAccountType(Integer accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waa_wallet_account.HOLD_ORDER_TIME
     *
     * @return the value of waa_wallet_account.HOLD_ORDER_TIME
     *
     * @mbg.generated
     */
    public String getHoldOrderTime() {
        return holdOrderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waa_wallet_account.HOLD_ORDER_TIME
     *
     * @param holdOrderTime the value for waa_wallet_account.HOLD_ORDER_TIME
     *
     * @mbg.generated
     */
    public void setHoldOrderTime(String holdOrderTime) {
        this.holdOrderTime = holdOrderTime == null ? null : holdOrderTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waa_wallet_account.AUTO_PAY_STATUS
     *
     * @return the value of waa_wallet_account.AUTO_PAY_STATUS
     *
     * @mbg.generated
     */
    public String getAutoPayStatus() {
        return autoPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waa_wallet_account.AUTO_PAY_STATUS
     *
     * @param autoPayStatus the value for waa_wallet_account.AUTO_PAY_STATUS
     *
     * @mbg.generated
     */
    public void setAutoPayStatus(String autoPayStatus) {
        this.autoPayStatus = autoPayStatus == null ? null : autoPayStatus.trim();
    }
}