package com.neusoft.bsp.model;

import java.math.BigDecimal;
import java.util.Date;

public class walletTransactionAduit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wta_wallet_transaction_aduit.TRANSACTION_AUDIT_ID
     *
     * @mbg.generated
     */
    private Integer transactionAuditId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wta_wallet_transaction_aduit.BUYER_ID
     *
     * @mbg.generated
     */
    private Integer buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wta_wallet_transaction_aduit.TRANSACTION_ID
     *
     * @mbg.generated
     */
    private Integer transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wta_wallet_transaction_aduit.AVAILABLE_MONEY_BEFORE
     *
     * @mbg.generated
     */
    private BigDecimal availableMoneyBefore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wta_wallet_transaction_aduit.DEPOSITING_MONEY_BEFORE
     *
     * @mbg.generated
     */
    private BigDecimal depositingMoneyBefore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wta_wallet_transaction_aduit.WITHDRAWING_MONEY_BEFORE
     *
     * @mbg.generated
     */
    private BigDecimal withdrawingMoneyBefore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wta_wallet_transaction_aduit.OPERATE_MONEY
     *
     * @mbg.generated
     */
    private BigDecimal operateMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wta_wallet_transaction_aduit.OPERATE_TYPE
     *
     * @mbg.generated
     */
    private Byte operateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wta_wallet_transaction_aduit.AVAILABLE_MONEY_AFTER
     *
     * @mbg.generated
     */
    private BigDecimal availableMoneyAfter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wta_wallet_transaction_aduit.DEPOSITING_MONEY_AFTER
     *
     * @mbg.generated
     */
    private BigDecimal depositingMoneyAfter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wta_wallet_transaction_aduit.WITHDRAWING_MONEY_AFTER
     *
     * @mbg.generated
     */
    private BigDecimal withdrawingMoneyAfter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wta_wallet_transaction_aduit.OPERATE_BY
     *
     * @mbg.generated
     */
    private String operateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wta_wallet_transaction_aduit.STATUS
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wta_wallet_transaction_aduit.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wta_wallet_transaction_aduit.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wta_wallet_transaction_aduit.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wta_wallet_transaction_aduit.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wta_wallet_transaction_aduit
     *
     * @mbg.generated
     */
    public walletTransactionAduit(Integer transactionAuditId, Integer buyerId, Integer transactionId, BigDecimal availableMoneyBefore, BigDecimal depositingMoneyBefore, BigDecimal withdrawingMoneyBefore, BigDecimal operateMoney, Byte operateType, BigDecimal availableMoneyAfter, BigDecimal depositingMoneyAfter, BigDecimal withdrawingMoneyAfter, String operateBy, Byte status, String createBy, Date createTime, String lastUpdateBy, Date lastUpdateTime) {
        this.transactionAuditId = transactionAuditId;
        this.buyerId = buyerId;
        this.transactionId = transactionId;
        this.availableMoneyBefore = availableMoneyBefore;
        this.depositingMoneyBefore = depositingMoneyBefore;
        this.withdrawingMoneyBefore = withdrawingMoneyBefore;
        this.operateMoney = operateMoney;
        this.operateType = operateType;
        this.availableMoneyAfter = availableMoneyAfter;
        this.depositingMoneyAfter = depositingMoneyAfter;
        this.withdrawingMoneyAfter = withdrawingMoneyAfter;
        this.operateBy = operateBy;
        this.status = status;
        this.createBy = createBy;
        this.createTime = createTime;
        this.lastUpdateBy = lastUpdateBy;
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wta_wallet_transaction_aduit
     *
     * @mbg.generated
     */
    public walletTransactionAduit() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wta_wallet_transaction_aduit.TRANSACTION_AUDIT_ID
     *
     * @return the value of wta_wallet_transaction_aduit.TRANSACTION_AUDIT_ID
     *
     * @mbg.generated
     */
    public Integer getTransactionAuditId() {
        return transactionAuditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wta_wallet_transaction_aduit.TRANSACTION_AUDIT_ID
     *
     * @param transactionAuditId the value for wta_wallet_transaction_aduit.TRANSACTION_AUDIT_ID
     *
     * @mbg.generated
     */
    public void setTransactionAuditId(Integer transactionAuditId) {
        this.transactionAuditId = transactionAuditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wta_wallet_transaction_aduit.BUYER_ID
     *
     * @return the value of wta_wallet_transaction_aduit.BUYER_ID
     *
     * @mbg.generated
     */
    public Integer getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wta_wallet_transaction_aduit.BUYER_ID
     *
     * @param buyerId the value for wta_wallet_transaction_aduit.BUYER_ID
     *
     * @mbg.generated
     */
    public void setBuyerId(Integer buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wta_wallet_transaction_aduit.TRANSACTION_ID
     *
     * @return the value of wta_wallet_transaction_aduit.TRANSACTION_ID
     *
     * @mbg.generated
     */
    public Integer getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wta_wallet_transaction_aduit.TRANSACTION_ID
     *
     * @param transactionId the value for wta_wallet_transaction_aduit.TRANSACTION_ID
     *
     * @mbg.generated
     */
    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wta_wallet_transaction_aduit.AVAILABLE_MONEY_BEFORE
     *
     * @return the value of wta_wallet_transaction_aduit.AVAILABLE_MONEY_BEFORE
     *
     * @mbg.generated
     */
    public BigDecimal getAvailableMoneyBefore() {
        return availableMoneyBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wta_wallet_transaction_aduit.AVAILABLE_MONEY_BEFORE
     *
     * @param availableMoneyBefore the value for wta_wallet_transaction_aduit.AVAILABLE_MONEY_BEFORE
     *
     * @mbg.generated
     */
    public void setAvailableMoneyBefore(BigDecimal availableMoneyBefore) {
        this.availableMoneyBefore = availableMoneyBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wta_wallet_transaction_aduit.DEPOSITING_MONEY_BEFORE
     *
     * @return the value of wta_wallet_transaction_aduit.DEPOSITING_MONEY_BEFORE
     *
     * @mbg.generated
     */
    public BigDecimal getDepositingMoneyBefore() {
        return depositingMoneyBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wta_wallet_transaction_aduit.DEPOSITING_MONEY_BEFORE
     *
     * @param depositingMoneyBefore the value for wta_wallet_transaction_aduit.DEPOSITING_MONEY_BEFORE
     *
     * @mbg.generated
     */
    public void setDepositingMoneyBefore(BigDecimal depositingMoneyBefore) {
        this.depositingMoneyBefore = depositingMoneyBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wta_wallet_transaction_aduit.WITHDRAWING_MONEY_BEFORE
     *
     * @return the value of wta_wallet_transaction_aduit.WITHDRAWING_MONEY_BEFORE
     *
     * @mbg.generated
     */
    public BigDecimal getWithdrawingMoneyBefore() {
        return withdrawingMoneyBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wta_wallet_transaction_aduit.WITHDRAWING_MONEY_BEFORE
     *
     * @param withdrawingMoneyBefore the value for wta_wallet_transaction_aduit.WITHDRAWING_MONEY_BEFORE
     *
     * @mbg.generated
     */
    public void setWithdrawingMoneyBefore(BigDecimal withdrawingMoneyBefore) {
        this.withdrawingMoneyBefore = withdrawingMoneyBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wta_wallet_transaction_aduit.OPERATE_MONEY
     *
     * @return the value of wta_wallet_transaction_aduit.OPERATE_MONEY
     *
     * @mbg.generated
     */
    public BigDecimal getOperateMoney() {
        return operateMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wta_wallet_transaction_aduit.OPERATE_MONEY
     *
     * @param operateMoney the value for wta_wallet_transaction_aduit.OPERATE_MONEY
     *
     * @mbg.generated
     */
    public void setOperateMoney(BigDecimal operateMoney) {
        this.operateMoney = operateMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wta_wallet_transaction_aduit.OPERATE_TYPE
     *
     * @return the value of wta_wallet_transaction_aduit.OPERATE_TYPE
     *
     * @mbg.generated
     */
    public Byte getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wta_wallet_transaction_aduit.OPERATE_TYPE
     *
     * @param operateType the value for wta_wallet_transaction_aduit.OPERATE_TYPE
     *
     * @mbg.generated
     */
    public void setOperateType(Byte operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wta_wallet_transaction_aduit.AVAILABLE_MONEY_AFTER
     *
     * @return the value of wta_wallet_transaction_aduit.AVAILABLE_MONEY_AFTER
     *
     * @mbg.generated
     */
    public BigDecimal getAvailableMoneyAfter() {
        return availableMoneyAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wta_wallet_transaction_aduit.AVAILABLE_MONEY_AFTER
     *
     * @param availableMoneyAfter the value for wta_wallet_transaction_aduit.AVAILABLE_MONEY_AFTER
     *
     * @mbg.generated
     */
    public void setAvailableMoneyAfter(BigDecimal availableMoneyAfter) {
        this.availableMoneyAfter = availableMoneyAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wta_wallet_transaction_aduit.DEPOSITING_MONEY_AFTER
     *
     * @return the value of wta_wallet_transaction_aduit.DEPOSITING_MONEY_AFTER
     *
     * @mbg.generated
     */
    public BigDecimal getDepositingMoneyAfter() {
        return depositingMoneyAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wta_wallet_transaction_aduit.DEPOSITING_MONEY_AFTER
     *
     * @param depositingMoneyAfter the value for wta_wallet_transaction_aduit.DEPOSITING_MONEY_AFTER
     *
     * @mbg.generated
     */
    public void setDepositingMoneyAfter(BigDecimal depositingMoneyAfter) {
        this.depositingMoneyAfter = depositingMoneyAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wta_wallet_transaction_aduit.WITHDRAWING_MONEY_AFTER
     *
     * @return the value of wta_wallet_transaction_aduit.WITHDRAWING_MONEY_AFTER
     *
     * @mbg.generated
     */
    public BigDecimal getWithdrawingMoneyAfter() {
        return withdrawingMoneyAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wta_wallet_transaction_aduit.WITHDRAWING_MONEY_AFTER
     *
     * @param withdrawingMoneyAfter the value for wta_wallet_transaction_aduit.WITHDRAWING_MONEY_AFTER
     *
     * @mbg.generated
     */
    public void setWithdrawingMoneyAfter(BigDecimal withdrawingMoneyAfter) {
        this.withdrawingMoneyAfter = withdrawingMoneyAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wta_wallet_transaction_aduit.OPERATE_BY
     *
     * @return the value of wta_wallet_transaction_aduit.OPERATE_BY
     *
     * @mbg.generated
     */
    public String getOperateBy() {
        return operateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wta_wallet_transaction_aduit.OPERATE_BY
     *
     * @param operateBy the value for wta_wallet_transaction_aduit.OPERATE_BY
     *
     * @mbg.generated
     */
    public void setOperateBy(String operateBy) {
        this.operateBy = operateBy == null ? null : operateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wta_wallet_transaction_aduit.STATUS
     *
     * @return the value of wta_wallet_transaction_aduit.STATUS
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wta_wallet_transaction_aduit.STATUS
     *
     * @param status the value for wta_wallet_transaction_aduit.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wta_wallet_transaction_aduit.CREATE_BY
     *
     * @return the value of wta_wallet_transaction_aduit.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wta_wallet_transaction_aduit.CREATE_BY
     *
     * @param createBy the value for wta_wallet_transaction_aduit.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wta_wallet_transaction_aduit.CREATE_TIME
     *
     * @return the value of wta_wallet_transaction_aduit.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wta_wallet_transaction_aduit.CREATE_TIME
     *
     * @param createTime the value for wta_wallet_transaction_aduit.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wta_wallet_transaction_aduit.LAST_UPDATE_BY
     *
     * @return the value of wta_wallet_transaction_aduit.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wta_wallet_transaction_aduit.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for wta_wallet_transaction_aduit.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wta_wallet_transaction_aduit.LAST_UPDATE_TIME
     *
     * @return the value of wta_wallet_transaction_aduit.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wta_wallet_transaction_aduit.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for wta_wallet_transaction_aduit.LAST_UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}