package com.neusoft.bsp.model;

import java.util.Date;

public class wishlist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wit_wishlist.WIT_ID
     *
     * @mbg.generated
     */
    private Integer witId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wit_wishlist.DSR_ID
     *
     * @mbg.generated
     */
    private Integer dsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wit_wishlist.PRO_ID
     *
     * @mbg.generated
     */
    private Integer proId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wit_wishlist.CREATED_BY
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wit_wishlist.CREATION_DATE
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wit_wishlist.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    private String lastUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wit_wishlist.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wit_wishlist.CALL_CNT
     *
     * @mbg.generated
     */
    private Integer callCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wit_wishlist.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wit_wishlist.STS_CD
     *
     * @mbg.generated
     */
    private String stsCd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wit_wishlist
     *
     * @mbg.generated
     */
    public wishlist(Integer witId, Integer dsrId, Integer proId, String createdBy, Date creationDate, String lastUpdateBy, Date lastUpdateDate, Integer callCnt, String remark, String stsCd) {
        this.witId = witId;
        this.dsrId = dsrId;
        this.proId = proId;
        this.createdBy = createdBy;
        this.creationDate = creationDate;
        this.lastUpdateBy = lastUpdateBy;
        this.lastUpdateDate = lastUpdateDate;
        this.callCnt = callCnt;
        this.remark = remark;
        this.stsCd = stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wit_wishlist
     *
     * @mbg.generated
     */
    public wishlist() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wit_wishlist.WIT_ID
     *
     * @return the value of wit_wishlist.WIT_ID
     *
     * @mbg.generated
     */
    public Integer getWitId() {
        return witId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wit_wishlist.WIT_ID
     *
     * @param witId the value for wit_wishlist.WIT_ID
     *
     * @mbg.generated
     */
    public void setWitId(Integer witId) {
        this.witId = witId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wit_wishlist.DSR_ID
     *
     * @return the value of wit_wishlist.DSR_ID
     *
     * @mbg.generated
     */
    public Integer getDsrId() {
        return dsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wit_wishlist.DSR_ID
     *
     * @param dsrId the value for wit_wishlist.DSR_ID
     *
     * @mbg.generated
     */
    public void setDsrId(Integer dsrId) {
        this.dsrId = dsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wit_wishlist.PRO_ID
     *
     * @return the value of wit_wishlist.PRO_ID
     *
     * @mbg.generated
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wit_wishlist.PRO_ID
     *
     * @param proId the value for wit_wishlist.PRO_ID
     *
     * @mbg.generated
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wit_wishlist.CREATED_BY
     *
     * @return the value of wit_wishlist.CREATED_BY
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wit_wishlist.CREATED_BY
     *
     * @param createdBy the value for wit_wishlist.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wit_wishlist.CREATION_DATE
     *
     * @return the value of wit_wishlist.CREATION_DATE
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wit_wishlist.CREATION_DATE
     *
     * @param creationDate the value for wit_wishlist.CREATION_DATE
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wit_wishlist.LAST_UPDATE_BY
     *
     * @return the value of wit_wishlist.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wit_wishlist.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for wit_wishlist.LAST_UPDATE_BY
     *
     * @mbg.generated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wit_wishlist.LAST_UPDATE_DATE
     *
     * @return the value of wit_wishlist.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wit_wishlist.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for wit_wishlist.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wit_wishlist.CALL_CNT
     *
     * @return the value of wit_wishlist.CALL_CNT
     *
     * @mbg.generated
     */
    public Integer getCallCnt() {
        return callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wit_wishlist.CALL_CNT
     *
     * @param callCnt the value for wit_wishlist.CALL_CNT
     *
     * @mbg.generated
     */
    public void setCallCnt(Integer callCnt) {
        this.callCnt = callCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wit_wishlist.REMARK
     *
     * @return the value of wit_wishlist.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wit_wishlist.REMARK
     *
     * @param remark the value for wit_wishlist.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wit_wishlist.STS_CD
     *
     * @return the value of wit_wishlist.STS_CD
     *
     * @mbg.generated
     */
    public String getStsCd() {
        return stsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wit_wishlist.STS_CD
     *
     * @param stsCd the value for wit_wishlist.STS_CD
     *
     * @mbg.generated
     */
    public void setStsCd(String stsCd) {
        this.stsCd = stsCd == null ? null : stsCd.trim();
    }
}