##test login

##1 login success
POST http://127.0.0.1:8088/user/login
Content-Type: application/json

{
  "username": "a",
  "password": "a"

}

###2 login wrong password
POST http://127.0.0.1:8088/user/login
Content-Type: application/json

{
  "username": "a",
  "password": "b"

}

###3 login no user
POST http://127.0.0.1:8088/user/login
Content-Type: application/json

{
  "username": "h",
  "password": "a"

}


###test register
###1 register MVO success
POST http://127.0.0.1:8088/user/register
Content-Type: application/json

{
  "username": "6",
  "password": "6",
  "role_id": "1"

}

###2 register BVO
POST http://127.0.0.1:8088/user/register
Content-Type: application/json

{
  "username": "7",
  "password": "7",
  "role_id": "2"

}

###3 same username
POST http://127.0.0.1:8088/user/register
Content-Type: application/json

{
  "username": "7",
  "password": "7",
  "role_id": "2"

}

###