package com.neusoft.bsp.dao;

import com.neusoft.bsp.model.andorra;

public interface andorraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_andorra
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_andorra
     *
     * @mbg.generated
     */
    int insert(andorra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_andorra
     *
     * @mbg.generated
     */
    int insertSelective(andorra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_andorra
     *
     * @mbg.generated
     */
    andorra selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_andorra
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(andorra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_andorra
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(andorra record);
}