package com.neusoft.bsp.dao;

import com.neusoft.bsp.model.codeMaster;

public interface codeMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdm_code_master
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cdmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdm_code_master
     *
     * @mbg.generated
     */
    int insert(codeMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdm_code_master
     *
     * @mbg.generated
     */
    int insertSelective(codeMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdm_code_master
     *
     * @mbg.generated
     */
    codeMaster selectByPrimaryKey(Integer cdmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdm_code_master
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(codeMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdm_code_master
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(codeMaster record);
}