package com.neusoft.bsp.dao;

import com.neusoft.bsp.model.dropshipper;

public interface dropshipperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsr_dropshipper
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer dsrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsr_dropshipper
     *
     * @mbg.generated
     */
    int insert(dropshipper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsr_dropshipper
     *
     * @mbg.generated
     */
    int insertSelective(dropshipper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsr_dropshipper
     *
     * @mbg.generated
     */
    dropshipper selectByPrimaryKey(Integer dsrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsr_dropshipper
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(dropshipper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsr_dropshipper
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(dropshipper record);
}