package com.neusoft.bsp.dao;

import com.neusoft.bsp.model.governmentArea;

public interface governmentAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goa_government_area
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer goaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goa_government_area
     *
     * @mbg.generated
     */
    int insert(governmentArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goa_government_area
     *
     * @mbg.generated
     */
    int insertSelective(governmentArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goa_government_area
     *
     * @mbg.generated
     */
    governmentArea selectByPrimaryKey(Integer goaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goa_government_area
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(governmentArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goa_government_area
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(governmentArea record);
}