package com.neusoft.bsp.dao;

import com.neusoft.bsp.model.image;

public interface imageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_image
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_image
     *
     * @mbg.generated
     */
    int insert(image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_image
     *
     * @mbg.generated
     */
    int insertSelective(image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_image
     *
     * @mbg.generated
     */
    image selectByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(image record);
}