package com.neusoft.bsp.dao;

import com.neusoft.bsp.model.monitorResult;

public interface monitorResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mor_monitor_result
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer morId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mor_monitor_result
     *
     * @mbg.generated
     */
    int insert(monitorResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mor_monitor_result
     *
     * @mbg.generated
     */
    int insertSelective(monitorResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mor_monitor_result
     *
     * @mbg.generated
     */
    monitorResult selectByPrimaryKey(Integer morId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mor_monitor_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(monitorResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mor_monitor_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(monitorResult record);
}