package com.neusoft.bsp.dao;

import com.neusoft.bsp.model.packageInfo;

public interface packageInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer pckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    int insert(packageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    int insertSelective(packageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    packageInfo selectByPrimaryKey(Integer pckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(packageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(packageInfo record);
}