package com.neusoft.bsp.dao;

import com.neusoft.bsp.model.parameter;

public interface parameterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table par_parameter
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer parId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table par_parameter
     *
     * @mbg.generated
     */
    int insert(parameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table par_parameter
     *
     * @mbg.generated
     */
    int insertSelective(parameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table par_parameter
     *
     * @mbg.generated
     */
    parameter selectByPrimaryKey(Integer parId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table par_parameter
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(parameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table par_parameter
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(parameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table par_parameter
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(parameter record);
}