package com.neusoft.bsp.dao;

import com.neusoft.bsp.model.productCategory;

public interface productCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer prcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    int insert(productCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    int insertSelective(productCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    productCategory selectByPrimaryKey(Integer prcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(productCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prc_product_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(productCategory record);
}