package com.neusoft.bsp.dao;

import com.neusoft.bsp.model.shippingAddress;

public interface shippingAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sha_shipping_address
     *
     * @mbg.generated
     */
    int insert(shippingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sha_shipping_address
     *
     * @mbg.generated
     */
    int insertSelective(shippingAddress record);
}