package com.neusoft.bsp.dao;

import com.neusoft.bsp.model.specifiAttribute;

public interface specifiAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spa_specific_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer spaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spa_specific_attribute
     *
     * @mbg.generated
     */
    int insert(specifiAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spa_specific_attribute
     *
     * @mbg.generated
     */
    int insertSelective(specifiAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spa_specific_attribute
     *
     * @mbg.generated
     */
    specifiAttribute selectByPrimaryKey(Integer spaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spa_specific_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(specifiAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spa_specific_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(specifiAttribute record);
}