package com.neusoft.bsp.dao;

import com.neusoft.bsp.model.specificAttributeValue;

public interface specificAttributeValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spv_specific_attribute_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer spvId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spv_specific_attribute_value
     *
     * @mbg.generated
     */
    int insert(specificAttributeValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spv_specific_attribute_value
     *
     * @mbg.generated
     */
    int insertSelective(specificAttributeValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spv_specific_attribute_value
     *
     * @mbg.generated
     */
    specificAttributeValue selectByPrimaryKey(Integer spvId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spv_specific_attribute_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(specificAttributeValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spv_specific_attribute_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(specificAttributeValue record);
}