package com.neusoft.bsp.dao;

import com.neusoft.bsp.model.storeOrderLineItem;

public interface storeOrderLineItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sol_store_order_line_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer solId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sol_store_order_line_item
     *
     * @mbg.generated
     */
    int insert(storeOrderLineItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sol_store_order_line_item
     *
     * @mbg.generated
     */
    int insertSelective(storeOrderLineItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sol_store_order_line_item
     *
     * @mbg.generated
     */
    storeOrderLineItem selectByPrimaryKey(Integer solId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sol_store_order_line_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(storeOrderLineItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sol_store_order_line_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(storeOrderLineItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sol_store_order_line_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(storeOrderLineItem record);
}