package com.neusoft.bsp.dao;

import com.neusoft.bsp.model.storeDropshipItem;

public interface storeDropshipItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdi_store_dropship_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer dilId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdi_store_dropship_item
     *
     * @mbg.generated
     */
    int insert(storeDropshipItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdi_store_dropship_item
     *
     * @mbg.generated
     */
    int insertSelective(storeDropshipItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdi_store_dropship_item
     *
     * @mbg.generated
     */
    storeDropshipItem selectByPrimaryKey(Integer dilId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdi_store_dropship_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(storeDropshipItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdi_store_dropship_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(storeDropshipItem record);
}