package com.neusoft.bsp.dao;

import com.neusoft.bsp.model.store;

public interface storeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table str_store
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer strId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table str_store
     *
     * @mbg.generated
     */
    int insert(store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table str_store
     *
     * @mbg.generated
     */
    int insertSelective(store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table str_store
     *
     * @mbg.generated
     */
    store selectByPrimaryKey(Integer strId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table str_store
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table str_store
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(store record);
}