package com.neusoft.bsp.dao;

import com.neusoft.bsp.model.userloginLogoutLog;

public interface userloginLogoutLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ull_user_login_logout_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ullId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ull_user_login_logout_log
     *
     * @mbg.generated
     */
    int insert(userloginLogoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ull_user_login_logout_log
     *
     * @mbg.generated
     */
    int insertSelective(userloginLogoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ull_user_login_logout_log
     *
     * @mbg.generated
     */
    userloginLogoutLog selectByPrimaryKey(Integer ullId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ull_user_login_logout_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(userloginLogoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ull_user_login_logout_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(userloginLogoutLog record);
}