package com.neusoft.bsp.dao;

import com.neusoft.bsp.model.walletTransactionAduit;

public interface walletTransactionAduitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wta_wallet_transaction_aduit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer transactionAuditId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wta_wallet_transaction_aduit
     *
     * @mbg.generated
     */
    int insert(walletTransactionAduit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wta_wallet_transaction_aduit
     *
     * @mbg.generated
     */
    int insertSelective(walletTransactionAduit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wta_wallet_transaction_aduit
     *
     * @mbg.generated
     */
    walletTransactionAduit selectByPrimaryKey(Integer transactionAuditId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wta_wallet_transaction_aduit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(walletTransactionAduit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wta_wallet_transaction_aduit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(walletTransactionAduit record);
}