package com.neusoft.bsp.dao;

import com.neusoft.bsp.model.walletAccountFund;

public interface walletAccountFundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waf_wallet_account_fund
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer buyerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waf_wallet_account_fund
     *
     * @mbg.generated
     */
    int insert(walletAccountFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waf_wallet_account_fund
     *
     * @mbg.generated
     */
    int insertSelective(walletAccountFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waf_wallet_account_fund
     *
     * @mbg.generated
     */
    walletAccountFund selectByPrimaryKey(Integer buyerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waf_wallet_account_fund
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(walletAccountFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waf_wallet_account_fund
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(walletAccountFund record);
}