package com.neusoft.bsp.dao;

import com.neusoft.bsp.model.walletTransactionRecord;

public interface walletTransactionRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wtr_wallet_transaction_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer transactionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wtr_wallet_transaction_record
     *
     * @mbg.generated
     */
    int insert(walletTransactionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wtr_wallet_transaction_record
     *
     * @mbg.generated
     */
    int insertSelective(walletTransactionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wtr_wallet_transaction_record
     *
     * @mbg.generated
     */
    walletTransactionRecord selectByPrimaryKey(Integer transactionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wtr_wallet_transaction_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(walletTransactionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wtr_wallet_transaction_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(walletTransactionRecord record);
}