package com.neusoft.bsp.dao;

import com.neusoft.bsp.business.po.wishlist;

public interface wishlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wit_wishlist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer witId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wit_wishlist
     *
     * @mbg.generated
     */
    int insert(wishlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wit_wishlist
     *
     * @mbg.generated
     */
    int insertSelective(wishlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wit_wishlist
     *
     * @mbg.generated
     */
    wishlist selectByPrimaryKey(Integer witId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wit_wishlist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(wishlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wit_wishlist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(wishlist record);
}